import work from "../../assets/work.png";
import activeWork from "../../assets/work-active.png";
import transport from "../../assets/transport.png";
import activeTransport from "../../assets/transport-active.png";
import estate from "../../assets/estate.png";
import activeEstate from "../../assets/estate-active.png";
import electronics from "../../assets/electrical-devices.png";
import activeElectronics from "../../assets/electrical-devices-active.png";
import dresses from "../../assets/dresses.png";
import activeDresses from "../../assets/dresses-active.png";
import building from "../../assets/building.png";
import activeBuilding from "../../assets/building-active.png";
import home from "../../assets/home.png";
import activeHome from "../../assets/home-active.png";
import services from "../../assets/services.png";
import activeServices from "../../assets/services-active.png";
import children from "../../assets/children.png";
import activeChildren from "../../assets/children-active.png";
import animals from "../../assets/animals.png";
import activeAnimals from "../../assets/animals-active.png";
import agriculture from "../../assets/agriculture.png";
import activeAgriculture from "../../assets/agriculture-active.png";
import holiday from "../../assets/holiday.png";
import activeHoliday from "../../assets/holiday-active.png";
import gifts from "../../assets/gifts.png";
import activeGifts from "../../assets/gifts-active.png";
import providers from "../../assets/provider.png";
import activeProviders from "../../assets/provider-active.png";

export const categories = [
  {
    name: "workAndBusiness",
    rus: "Работа и бизнес",
    eng: "Work and business",
    uzb: "Ish va biznes",
    pic: work,
    activePic: activeWork,
    path: "work-and-business",
    id: 1,
    types: [
      {
        name: "vacancies",
        path: "vacancies",
        rus: "Вакансии",
        eng: "Vacancies",
        uzb: "Bo'sh ish o'rinlari",
        types: [
          {
            name: "retail",
            path: "retail",
            rus: "Розничная торговля / Продажи",
            eng: "Retail / Sales",
            uzb: "Chakana savdo / sotish",
            types: [
              {
                name: "seller",
                path: "seller",
                rus: "Продавец",
                eng: "Seller",
                uzb: "Sotuvchi",
              },
              {
                name: "salesConsultant",
                path: "sales-consultant",
                rus: "Продавец консультант",
                eng: "Sales consultant",
                uzb: "Sotuvchi maslahatchisi",
              },
              {
                name: "salesRepresentative",
                path: "sales-representative",
                rus: "Торговый представитель",
                eng: "Sales Representative",
                uzb: "Savdo vakili",
              },
              {
                name: "salesManager",
                path: "Sales-manager",
                rus: "Менеджер по продажам",
                eng: "Sales Manager",
                uzb: "Savdo menejeri",
              },
              {
                name: "merchandiser",
                path: "merchandiser",
                rus: "Мерчандайзер",
                eng: "Merchandiser",
                uzb: "Merchandayzer",
              },
              {
                name: "cashier",
                path: "cashier",
                rus: "Кассир",
                eng: "Cashier",
                uzb: "Kassir",
              },
              {
                name: "florist",
                path: "florist",
                rus: "Флорист",
                eng: "Florist",
                uzb: "Florist",
              },
              {
                name: "storeSalesFloorAdministrator",
                path: "store-sales-floor-administrator",
                rus: "Администратор магазина / торгового зала",
                eng: "Store / sales floor administrator",
                uzb: "Do'kon / savdo maydonchasi ma'muri",
              },
              {
                name: "supplyManager",
                path: "supply-manager",
                rus: "Менеджер по снабжению",
                eng: "Supply Manager",
                uzb: "Ta'minot menejeri",
              },
              {
                name: "onlineStoreManager",
                path: "online-store-manager",
                rus: "Менеджер интернет-магазина",
                eng: "Online store Manager",
                uzb: "Onlayn do'kon menejeri",
              },
              {
                name: "other",
                path: "other",
                rus: "Другое",
                eng: "Other",
                uzb: "Boshqa",
              },
            ],
          },
          {
            name: "transport",
            path: "transport",
            rus: "Транспорт / логистика",
            eng: "Transport / logistics",
            uzb: "Transport / logistika",
            types: [
              {
                name: "driver",
                path: "driver",
                rus: "Водитель",
                eng: "Driver",
                uzb: "Haydovchi",
              },
              {
                name: "courier",
                path: "courier",
                rus: "Курьер",
                eng: "Courier",
                uzb: "Kuryer",
              },
              {
                name: "loader",
                path: "loader",
                rus: "Грузчик",
                eng: "Loader",
                uzb: "Yuklovchi",
              },
              {
                name: "freightForwarder",
                path: "freight-forwarder",
                rus: "Экспедитор",
                eng: "Freight Forwarder",
                uzb: "Ekspeditor",
              },
              {
                name: "machinist",
                path: "machinist",
                rus: "Машинист",
                eng: "Machinist",
                uzb: "Haydovchi",
              },
              {
                name: "trucker",
                path: "trucker",
                rus: "Дальнобойщик",
                eng: "Trucker",
                uzb: "Yuk mashina haydovchisi",
              },
              {
                name: "logistician",
                path: "logistician",
                rus: "Логист",
                eng: "Logistician",
                uzb: "Logist",
              },
              {
                name: "orderPicker",
                path: "order-picker",
                rus: "Комплектовщик",
                eng: "Order picker",
                uzb: "Buyurtma tanlovchi",
              },
              {
                name: "dispatcher",
                path: "dispatcher",
                rus: "Диспетчер",
                eng: "Dispatcher",
                uzb: "Dispetcher",
              },
              {
                name: "taxi",
                path: "taxi",
                rus: "Работа в такси",
                eng: "Taxi",
                uzb: "Taksida ishlash",
              },
              {
                name: "other",
                path: "other",
                rus: "Другое",
                eng: "Other",
                uzb: "Boshqa",
              },
            ],
          },
          {
            name: "building",
            path: "building",
            rus: "Строительство",
            eng: "Building",
            uzb: "Qurilish",
            types: [
              {
                name: "handyman",
                path: "handyman",
                rus: "Разнорабочий",
                eng: "Handyman",
                uzb: "Hunarmand",
              },
              {
                name: "welder",
                path: "welder",
                rus: "Сварщик",
                eng: "Welder",
                uzb: "Payvandchi",
              },
              {
                name: "installer",
                path: "installer",
                rus: "Монтажник / Установщик",
                eng: "Installer",
                uzb: "O'rnatuvchi",
              },
              {
                name: "electrician",
                path: "electrician",
                rus: "Электромонтажник",
                eng: "Electrician",
                uzb: "Elektr ustasi",
              },
              {
                name: "plumber",
                path: "plumber",
                rus: "Сантехник",
                eng: "Plumber",
                uzb: "Santexnik",
              },
              {
                name: "bricklayer",
                path: "bricklayer",
                rus: "Каменщик",
                eng: "Bricklayer",
                uzb: "Kamenchi",
              },
              {
                name: "locksmith",
                path: "locksmith",
                rus: "Слесарь",
                eng: "Locksmith",
                uzb: "Chilangar",
              },
              {
                name: "carpenter",
                path: "carpenter",
                rus: "Плотник",
                eng: "Carpenter",
                uzb: "",
              },
              {
                name: "painter",
                path: "painter",
                rus: "Маляр",
                eng: "Painter",
                uzb: "Rassom",
              },
              {
                name: "foreman",
                path: "foreman",
                rus: "Прораб",
                eng: "Foreman",
                uzb: "Usta",
              },
              {
                name: "concreteWorker",
                path: "concrete-worker",
                rus: "Бетонщик",
                eng: "Concrete worker",
                uzb: "Betonchi",
              },
              {
                name: "fitter",
                path: "fitter",
                rus: "Арматурщик",
                eng: "Fitter",
                uzb: "Armaturchi",
              },
              {
                name: "plasterer",
                path: "plasterer",
                rus: "Штукатур",
                eng: "Plasterer",
                uzb: "Shivachi",
              },
              {
                name: "surveyor",
                path: "surveyor",
                rus: "Геодезист",
                eng: "Surveyor",
                uzb: "Geodezist",
              },
              {
                name: "interiorDesigner",
                path: "interior-designer",
                rus: "Дизайнер интерьера",
                eng: "Interior designer",
                uzb: "Interyer dizayneri",
              },
              {
                name: "craneOperator",
                path: "crane-operator",
                rus: "Машинист крана",
                eng: "Crane operator",
                uzb: "Kran operatori",
              },
              {
                name: "designer",
                path: "designer",
                rus: "Проектировщик",
                eng: "Designer",
                uzb: "Dizayner",
              },
              {
                name: "industrialClimber",
                path: "Industrial-climber",
                rus: "Промышленный альпинист",
                eng: "Industrial climber",
                uzb: "Sanoat alpinisti",
              },
              {
                name: "estimator",
                path: "estimator",
                rus: "Сметчик",
                eng: "Estimator",
                uzb: "Baholovchi",
              },
              {
                name: "architect",
                path: "architect",
                rus: "Архитектор",
                eng: "Architect",
                uzb: "Arxitektor",
              },
              {
                name: "roadConstruction",
                path: "roadConstruction",
                rus: "Строительство дорог",
                eng: "Road construction",
                uzb: "Yo'l qurilishi",
              },
              {
                name: "other",
                path: "other",
                rus: "Другое",
                eng: "Other",
                uzb: "Boshqa",
              },
            ],
          },
          {
            name: "restaurants",
            path: "restaurants",
            rus: "Бары / рестораны",
            eng: "Bar/Restaurant",
            uzb: "Bar/restoran",
          },
          {
            name: "jurisdiction",
            path: "jurisdiction",
            rus: "Юриспруденция и бухгалтерия",
            eng: "Jurisprudence and accounting",
            uzb: "Huquq va buxgalteriya hisobi",
          },
          {
            name: "security",
            path: "security",
            rus: "Охрана / безопасность",
            eng: "Security / security",
            uzb: "Xavfsizlik / xavfsizlik",
          },
          {
            name: "housePersonnel",
            path: "housePersonnel",
            rus: "Домашний персонал",
            eng: "Household staff",
            uzb: "Uy xodimlari",
          },
          {
            name: "beautyFitnessSport",
            path: "beautyFitnessSport",
            rus: "Красота / фитнес / спорт",
            eng: "Beauty / fitness / sports",
            uzb: "Go'zallik / fitnes / sport",
          },
          {
            name: "tourism",
            path: "tourism",
            rus: "Туризм / отдых / развлечения",
            eng: "Tourism / Leisure / Entertainment",
            uzb: "Turizm / Dam olish / O'yin-kulgi",
          },
          {
            name: "education",
            path: "education",
            rus: "Образование",
            eng: "Education",
            uzb: "Ta'lim",
          },
          {
            name: "culture",
            path: "culture",
            rus: "Культура / искусство",
            eng: "Culture / art",
            uzb: "Madaniyat / san'at",
          },
          {
            name: "medicine",
            path: "medicine",
            rus: "Медицина / фармация",
            eng: "Medicine / Pharmacy",
            uzb: "Tibbiyot / Dorixona",
          },
          {
            name: "it",
            path: "it",
            rus: "ИТ / телеком / компьютеры",
            eng: "IT / telecom / computers",
            uzb: "IT / telekom / kompyuterlar",
          },
          {
            name: "realEstate",
            path: "realEstate",
            rus: "Недвижимость",
            eng: "Real estate",
            uzb: "Ko `chmas mulk",
            types: [
              {
                name: "Realtor",
                path: "Realtor",
                rus: "Риэлтор",
                eng: "Realtor",
                uzb: "Rieltor",
              },
              {
                name: "realEstateSalesManager",
                path: "real-estate-sales-manager",
                rus: "Менеджер по продажам недвижимости",
                eng: "Real Estate Sales Manager",
                uzb: "Ko'chmas mulkni sotish bo'yicha menejer",
              },
              {
                name: "other",
                path: "other",
                rus: "Другое",
                eng: "Other",
                uzb: "Boshqa",
              },
            ],
          },
          {
            name: "marketing",
            path: "marketing",
            rus: "Маркетинг / реклама / дизайн",
            eng: "Marketing / advertising / design",
            uzb: "Marketing / reklama / dizayn",
          },
          {
            name: "manufacture",
            path: "manufacture",
            rus: "Производство / энергетика",
            eng: "Manufacturing / energy",
            uzb: "Ishlab chiqarish / energiya",
          },
          {
            name: "secretarian",
            path: "secretarian",
            rus: "Cекретариат / АХО",
            eng: "Secretariat / AHO",
            uzb: "Kotibiyat / AHO",
          },
          {
            name: "services",
            path: "services",
            rus: "Сервис и быт",
            eng: "Service and life",
            uzb: "Xizmat va hayot",
          },
          {
            name: "otherOccupations",
            path: "others-occupations",
            rus: "Другие сферы занятий",
            eng: "Other occupations",
            uzb: "Boshqa kasblar",
          },
        ],
      },
      {
        name: "lookingForJob",
        rus: "Ищут работу",
        eng: "Looking for job",
        uzb: "Ish qidirish",
        path: "jobs",
      },
      {
        name: "coursesEducation",
        rus: "Курсы, образование",
        eng: "Courses, education",
        uzb: "Kurslar, ta'lim",
        path: "coursesEducation",
      },
      {
        name: "legalServices",
        rus: "Юридические услуги",
        eng: "Legal services",
        uzb: "Yuridik xizmatlar",
        path: "legalServices",
      },
      {
        name: "financialServices",
        rus: "Финансовые услуги",
        eng: "Financial services",
        uzb: "Moliyaviy xizmatlar",
        path: "financialServices",
      },
      {
        name: "internetServices",
        rus: "Интернет-услуги",
        eng: "Internet services",
        uzb: "Internet xizmatlari",
        path: "internetServices",
      },
      {
        name: "other",
        rus: "Разное",
        eng: "Others",
        uzb: "Boshqalar",
        path: "other",
      },
    ],
  },
  {
    name: "transport",
    path: "transport",
    rus: "Транспорт",
    eng: "Transport",
    uzb: "Transport",
    pic: transport,
    activePic: activeTransport,
    id: 2,
    types: [
      {
        name: "cars",
        path: "cars",
        rus: "Легковые авто",
        eng: "Cars",
        uzb: "Yengil mashinalar",
        types: [
          {
            name: "Chevrolet",
            eng: "Chevrolet",
            uzb: "Chevrolet",
            rus: "Chevrolet",
          },
          { name: "Audi", eng: "Audi", uzb: "Audi", rus: "Audi" },
          { name: "Baic", eng: "Baic", uzb: "Baic", rus: "Baic" },
          { name: "BMW", eng: "BMW", uzb: "BMW", rus: "BMW" },
          { name: "BYD", eng: "BYD", uzb: "BYD", rus: "BYD" },
          { name: "Daewoo", eng: "Daewoo", uzb: "Daewoo", rus: "Daewoo" },
          { name: "Denza", eng: "Denza", uzb: "Denza", rus: "Denza" },
          { name: "Fiat", eng: "Fiat", uzb: "Fiat", rus: "Fiat" },
          { name: "Ford", eng: "Ford", uzb: "Ford", rus: "Ford" },
          { name: "GAC", eng: "GAC", uzb: "GAC", rus: "GAC" },
          { name: "Haval", eng: "Haval", uzb: "Haval", rus: "Haval" },
          { name: "Hyundai", eng: "Hyundai", uzb: "Hyundai", rus: "Hyundai" },
          { name: "Isuzu", eng: "Isuzu", uzb: "Isuzu", rus: "Isuzu" },
          { name: "JAC", eng: "JAC", uzb: "JAC", rus: "JAC" },
          { name: "Kia", eng: "Kia", uzb: "Kia", rus: "Kia" },
          { name: "Lexus", eng: "Lexus", uzb: "Lexus", rus: "Lexus" },
          { name: "Mazda", eng: "Mazda", uzb: "Mazda", rus: "Mazda" },
          {
            name: "Mercedes",
            eng: "Mercedes",
            uzb: "Mercedes",
            rus: "Mercedes",
          },
          {
            name: "Mitsubishi",
            eng: "Mitsubishi",
            uzb: "Mitsubishi",
            rus: "Mitsubishi",
          },
          { name: "Nio", eng: "Nio", uzb: "Nio", rus: "Nio" },
          { name: "Nissan", eng: "Nissan", uzb: "Nissan", rus: "Nissan" },
          { name: "Opel", eng: "Opel", uzb: "Opel", rus: "Opel" },
          { name: "ORA", eng: "ORA", uzb: "ORA", rus: "ORA" },
          { name: "Peugeot", eng: "Peugeot", uzb: "Peugeot", rus: "Peugeot" },
          { name: "Porsche", eng: "Porsche", uzb: "Porsche", rus: "Porsche" },
          { name: "Skoda", eng: "Skoda", uzb: "Skoda", rus: "Skoda" },
          { name: "Tesla", eng: "Tesla", uzb: "Tesla", rus: "Tesla" },
          { name: "Toyota", eng: "Toyota", uzb: "Toyota", rus: "Toyota" },
          {
            name: "Volkswagen",
            eng: "Volkswagen",
            uzb: "Volkswagen",
            rus: "Volkswagen",
          },
          { name: "Xpeng", eng: "Xpeng", uzb: "Xpeng", rus: "Xpeng" },
          { name: "vaz", eng: "ВАЗ", uzb: "ВАЗ", rus: "ВАЗ" },
          { name: "gaz", eng: "ГАЗ", uzb: "ГАЗ", rus: "ГАЗ" },
          { name: "zaz", eng: "ЗАЗ", uzb: "ЗАЗ", rus: "ЗАЗ" },
          { name: "ij", eng: "ИЖ", uzb: "ИЖ", rus: "ИЖ" },
          { name: "moskvich", eng: "Москвич", uzb: "Москвич", rus: "Москвич" },
          { name: "uaz", eng: "УАЗ", uzb: "УАЗ", rus: "УАЗ" },
          { name: "others", eng: "others", uzb: "others", rus: "others" },
        ],
      },
      {
        name: "trucks",
        path: "trucks",
        rus: "Грузовые машины",
        eng: "Trucks",
        uzb: "Yuk mashinalar",
      },
      {
        name: "moto",
        path: "moto",
        rus: "Мото транспорт",
        eng: "Motorcycle transport",
        uzb: "Mototsikl transporti",
        types: [
          {
            name: "mopedsScooters",
            rus: "Мопеды / скутеры",
            eng: "Mopeds / scooters",
            uzb: "Mopedlar / skuterlar",
          },
          { name: "atvs", rus: "Квадроциклы", eng: "ATVs", uzb: "ATVlar" },
          {
            name: "motorcycles",
            rus: "Мотоциклы",
            eng: "Motorcycles",
            uzb: "Mototsikllar",
          },
          {
            name: "MotoOther",
            rus: "Мото - прочее",
            eng: "Moto - other",
            uzb: "Moto - boshqa",
          },
        ],
      },
      {
        name: "bikes",
        path: "bikes",
        rus: "Велосипеды, самокаты",
        eng: "Bicycles, scooters",
        uzb: "Velosipedlar, skuterlar",
      },

      {
        name: "repairAndSpareParts",
        path: "repair-and-spare-parts",
        rus: "Запчасти для авто и мото",
        eng: "Repair and spare parts",
        uzb: "Ta'mirlash va ehtiyot qismlar",
        carSpares: [
          {
            name: "autoParts",
            rus: "Автозапчасти",
            eng: "Auto parts",
            uzb: "Avtomobil qismlari",
          },
          {
            name: "autoAccessories",
            rus: "Аксессуары для авто",
            eng: "Auto accessories",
            uzb: "Avto aksessuarlar",
          },
          {
            name: "carAudio",
            rus: "Автозвук",
            eng: "Car audio",
            uzb: "Avtomobil audio",
          },
          {
            name: "transportForSpareParts",
            rus: "Транспорт на запчасти",
            eng: "Transport for spare parts",
            uzb: "Transport uchun ehtiyot qismlar",
          },
          {
            name: "GPSNavigatorsCarRecorders",
            rus: "GPS-навигаторы / авторегистраторы",
            eng: "GPS navigators / car recorders",
            uzb: "GPS navigatorlari / avtomobil yozuvchilari",
          },
        ],
        motoSpares: [
          {
            name: "motorcycleParts",
            rus: "Мотозапчасти",
            eng: "Motorcycle parts",
            uzb: "Mototsikl qismlari",
          },
          {
            name: "motoEquipment",
            rus: "Мотоэкипировка",
            eng: "Mototsikl equipment",
            uzb: "Motor uskunalari",
          },
          {
            name: "motoAccessories",
            rus: "Мото аксессуары",
            eng: "Moto accessories",
            uzb: "Moto aksessuarlar",
          },
        ],
        tiresWheels: [
          { name: "tires", rus: "Автошины", eng: "Tires", uzb: "Shinalar" },
          {
            name: "motoTires",
            rus: "Мотошины",
            eng: "Moto tires",
            uzb: "Moto shinalari",
          },
          { name: "disks", rus: "Диски", eng: "Disks", uzb: "Disklar" },
          {
            name: "Complete wheels",
            rus: "Колеса в сборе",
            eng: "Complete wheels",
            uzb: "To'liq g'ildiraklar",
          },
          { name: "caps", rus: "Колпаки", eng: "Caps", uzb: "Qopqoqlar" },
        ],
      },

      {
        name: "bus",
        path: "bus",
        rus: "Автобусы",
        eng: "Buses",
        uzb: "Avtobuslar",
      },
      {
        name: "trailers",
        path: "trailers",
        rus: "Прицепы",
        eng: "Trailers",
        uzb: "Treylerlar",
      },
      {
        name: "specialEquipment",
        path: "special-equipment",
        rus: "Спецтехника",
        eng: "Special machines",
        uzb: "Maxsus mashinalar",
      },
      {
        name: "agricultural",
        path: "agricultural-machinery",
        rus: "Сельхозтехника",
        eng: "Agricultural machines",
        uzb: "Qishloq xo'jaligi texnikasi",
      },
      {
        name: "sparesSpecialMachines",
        path: "spares-special-machines",
        rus: "Запчасти для техники",
        eng: "Spare parts for special/agricultural machines",
        uzb: "Maxsus/qishloq x. mashinalar ehtiyot qismlar",
      },
      {
        name: "waterTransport",
        path: "water-transport",
        rus: "Водный транспорт",
        eng: "Water transport",
        uzb: "Suv transporti",
      },
      {
        name: "other",
        path: "other-transport",
        rus: "Другое",
        eng: "Other",
        uzb: "Boshqalar",
      },
    ],
  },
  {
    name: "realEstate",
    path: "real-estate",
    rus: "Недвижимость",
    eng: "Real estate",
    uzb: "Ko'chmas mulk",
    pic: estate,
    activePic: activeEstate,
    id: 3,
    types: [
      {
        name: "apartments",
        eng: "Apartments",
        uzb: "Kvartiralar",
        rus: "Квартиры",
        types: [
          {
            name: "longTermRent",
            eng: "Long term rent",
            rus: "Аренда долгосрочная",
            uzb: "Uzoq muddatli ijara",
          },
          {
            name: "dailyHourlyRent",
            eng: "Daily/hourly rent",
            rus: "Аренда почасово, посуточно",
            uzb: "Kunlik/soatlik ijara",
          },
          {
            name: "forSell",
            eng: "Sale",
            rus: "Продажа",
            uzb: "Sotish",
          },
          {
            name: "exchange",
            eng: "Exchange",
            rus: "Обмен",
            uzb: "Almashish",
          },
        ],
      },
      {
        name: "houses",
        rus: "Дома, дачи",
        eng: "Houses, cottages",
        uzb: "Uylar, kottejlar",
        types: [
          {
            name: "longTermRent",
            eng: "Long term rent",
            rus: "Аренда долгосрочная",
            uzb: "Uzoq muddatli ijara",
          },
          {
            name: "dailyHourlyRent",
            eng: "Daily/hourly rent",
            rus: "Аренда почасово, посуточно",
            uzb: "Kunlik/soatlik ijara",
          },
          {
            name: "forSell",
            eng: "Sale",
            rus: "Продажа",
            uzb: "Sotish",
          },
          {
            name: "exchange",
            eng: "Exchange",
            rus: "Обмен",
            uzb: "Almashish",
          },
        ],
      },
      {
        name: "rooms",
        rus: "Комнаты",
        eng: "Rooms",
        uzb: "Xonalar",
        types: [
          {
            name: "longTermRent",
            eng: "Long term rent",
            rus: "Аренда долгосрочная",
            uzb: "Uzoq muddatli ijara",
          },
          {
            name: "dailyHourlyRent",
            eng: "Daily/hourly rent",
            rus: "Аренда почасово, посуточно",
            uzb: "Kunlik/soatlik ijara",
          },
          {
            name: "forSell",
            eng: "Sale",
            rus: "Продажа",
            uzb: "Sotish",
          },
        ],
      },
      {
        name: "offices",
        rus: "Коммерческие помещения",
        eng: "Offices",
        uzb: "Ofislar",
        types: [
          {
            name: "forSell",
            eng: "Sale",
            rus: "Продажа",
            uzb: "Sotish",
          },
          {
            name: "forRent",
            eng: "Rent",
            rus: "Аренда",
            uzb: "Ijara",
          },
        ],
      },
      {
        name: "landAndPlots",
        path: "land-and-plots",
        rus: "Земля и участки",
        eng: "Land and plots",
        uzb: "Yer va uchastkalar",
        types: [
          {
            name: "forSell",
            eng: "Sale",
            rus: "Продажа",
            uzb: "Sotish",
          },
          {
            name: "forRent",
            eng: "Rent",
            rus: "Аренда",
            uzb: "Ijara",
          },
        ],
      },
      {
        name: "garagesParking",
        rus: "Гаражи / стоянки",
        eng: "Garages / Parking",
        uzb: "Garajlar / To'xtash joyi",
        types: [
          {
            name: "forSell",
            eng: "Sale",
            rus: "Продажа",
            uzb: "Sotish",
          },
          {
            name: "forRent",
            eng: "Rent",
            rus: "Аренда",
            uzb: "Ijara",
          },
        ],
      },
      {
        name: "others",
        rus: "другое",
        uzb: "Boshqalar",
        eng: "Others",
      },
    ],
  },
  {
    name: "electronics",
    rus: "Электроника",
    eng: "Electronics",
    uzb: "Elektronika",
    pic: electronics,
    activePic: activeElectronics,
    path: "electronics",
    id: 4,
    types: [
      {
        name: "phones",
        path: "phones-communication",
        rus: "Телефоны и аксессуары",
        eng: "Phones and communications",
        uzb: "Telefonlar va aloqa",
        types: [
          {
            name: "accessories",
            rus: "Аксессуары для телефонов",
            eng: "Accessories for phones",
            uzb: "Telefon uchun aksessuarlar",
          },
          {
            name: "phoneParts",
            rus: "Запчасти для телефонов",
            eng: "Phone Parts",
            uzb: "Telefon qismlari",
          },
          {
            name: "smartphones",
            rus: "Смартфоны",
            eng: "Smartphones",
            uzb: "Smartfonlar",
          },
          {
            name: "SIMCardsTariffsNumbers",
            rus: "Сим-карты / тарифы / номера",
            eng: "SIM cards / tariffs / numbers",
            uzb: "SIM-kartalar / tariflar / raqamlar",
          },
          {
            name: "landlines",
            rus: "Стационарные телефоны",
            eng: "Landlines",
            uzb: "Statsionar telefonlar",
          },
          {
            name: "otherPhones",
            rus: "Рации и прочие телефоны",
            eng: "Walkie-talkie and other phones",
            uzb: "Ratsiya va boshqa telefonlar",
          },
        ],
      },
      {
        name: "computersOfficeEquipment",
        path: "computers-office-equipment",
        rus: "Компьютеры и комплектующие",
        eng: "Computers, office equipment",
        uzb: "Kompyuterlar, ofis jihozlari",
        types: [
          {
            name: "desktops",
            rus: "Настольные компьютеры",
            eng: "Desktop",
            uzb: "Shaxsiy komputerlar",
          },
          { name: "servers", rus: "Серверы", eng: "Servers", uzb: "Serverlar" },
          {
            name: "accessories",
            rus: "Аксессуары",
            eng: "Accessories",
            uzb: "Aksessuarlar",
          },
          {
            name: "peripherals",
            rus: "Периферийные устройства",
            eng: "Peripherals",
            uzb: "Periferik qurilmalar",
          },
          {
            name: "monitors",
            rus: "Мониторы",
            eng: "Monitors",
            uzb: "Monitorlar",
          },
          {
            name: "externalDrives",
            rus: "Внешние накопители",
            eng: "External drives",
            uzb: "Tashqi drayvlar",
          },
          {
            name: "expendableMaterials",
            rus: "Расходные материалы",
            eng: "Expendable materials",
            uzb: "Sarflanadigan materiallar",
          },
          { name: "other", rus: "Другое", eng: "Other", uzb: "Boshqa" },
        ],
      },
      {
        name: "appliances",
        path: "appliances",
        rus: "Бытовая техника",
        eng: "Appliances",
        uzb: "Maishiy texnika",
        types: [
          {
            name: "forHome",
            rus: "Техника для дома",
            eng: "Home Appliances",
            uzb: "Maishiy texnika",
            types: [
              {
                name: "vacuumCleaners",
                rus: "Пылесосы",
                eng: "Vacuum cleaners",
                uzb: "Chang yutgichlar",
              },
              { name: "irons", rus: "Утюги", eng: "Irons", uzb: "Dazmollar" },
              {
                name: "washingMachines",
                rus: "Стиральные машины",
                eng: "Washing machines",
                uzb: "Kir yuvish mashinalari",
              },
              {
                name: "sewingMachinesAndOverlockers",
                rus: "Швейные машины и оверлоки",
                eng: "Sewing machines and overlockers",
                uzb: "Tikuv mashinalari va overloklar",
              },
              {
                name: "knittingMachines",
                rus: "Вязальные машины",
                eng: "Knitting machines",
                uzb: "Trikotaj mashinalari",
              },
              {
                name: "waterFilters",
                rus: "Фильтры для воды",
                eng: "Water filters",
                uzb: "Suv filtrlari",
              },
              {
                name: "otherHomeAppliances",
                rus: "Прочая техника для дома",
                eng: "Other home appliances",
                uzb: "Boshqa maishiy texnika",
              },
            ],
          },
          {
            name: "forKitchen",
            rus: "Техника для кухни",
            eng: "Kitchen Appliances",
            uzb: "Oshxona jihozlari",
            types: [
              {
                name: "microwaves",
                rus: "Микроволновые печи",
                eng: "Microwaves",
                uzb: "Mikroto'lqinli pechlar",
              },
              {
                name: "refrigerators",
                rus: "Холодильники",
                eng: "Refrigerators",
                uzb: "Muzlatgichlar",
              },
              {
                name: "cookersOvens",
                rus: "Плиты / печи",
                eng: "Cookers / ovens",
                uzb: "Pechlar",
              },
              {
                name: "electricKettles",
                rus: "Электрочайники",
                eng: "Electric kettles",
                uzb: "Elektr choynaklar",
              },
              {
                name: "coffeeMakersCoffeeGrinders",
                rus: "Кофеварки / кофемолки",
                eng: "Coffee makers / coffee grinders",
                uzb: "Kofe qaynatgichlar / kofe maydalagichlar",
              },
              {
                name: "foodProcessorsAndChoppers",
                rus: "Кухонные комбайны и измельчители",
                eng: "Food processors and choppers",
                uzb: "Oziq-ovqat protsessorlari va maydalagichlar",
              },
              {
                name: "steamersMulticookers",
                rus: "Пароварки, мультиварки",
                eng: "Steamers, multicookers",
                uzb: "Bug'da pishirgichlar, ko'p pishirgichlar",
              },
              {
                name: "breadMakers",
                rus: "Хлебопечки",
                eng: "Bread makers",
                uzb: "Non ishlab chiqaruvchilar",
              },
              {
                name: "dishwashers",
                rus: "Посудомоечные машины",
                eng: "Dishwashers",
                uzb: "Idish yuvish mashinalari",
              },
              {
                name: "hoods",
                rus: "Вытяжки",
                eng: "Hoods",
                uzb: "Davlumbazlar",
              },
              {
                name: "otherKitchenAppliances",
                rus: "Прочая техника для кухни",
                eng: "Other kitchen appliances",
                uzb: "Boshqa oshxona jihozlari",
              },
            ],
          },
        ],
      },
      {
        name: "tvs",
        path: "tvs",
        rus: "Тв / видеотехника",
        eng: "TVs",
        uzb: "Televizorlar / Video texnika",
        types: [
          {
            name: "mediaPlayers",
            rus: "Медиа проигрыватели",
            eng: "Media players",
            uzb: "Media pleerlar",
          },
          { name: "tvs", rus: "Телевизоры", eng: "TVs", uzb: "Televizorlar" },
          {
            name: "projectors",
            rus: "Проекторы",
            eng: "Projectors",
            uzb: "Proyektorlar",
          },

          {
            name: "TV/VideoAccessories",
            rus: "Аксессуары для ТВ/Видеотехники",
            eng: "TV/Video Accessories",
            uzb: "TV/Video aksessuarlari",
          },
          {
            name: "satelliteTV",
            rus: "Спутниковое тв",
            eng: "Satellite TV",
            uzb: "Sun'iy yo'ldosh televideniesi",
          },
          {
            name: "other",
            rus: "Прочая тв / видеотехника",
            eng: "Other TV / video equipment",
            uzb: "Boshqa televizor / video uskunalari",
          },
        ],
      },
      {
        name: "audioVideoDVDSSAT",
        path: "audio-video",
        rus: "Аудио",
        eng: "Audio",
        uzb: "Audio",
        types: [
          {
            name: "headphones",
            rus: "Наушники",
            eng: "Headphones",
            uzb: "Naushniklar",
          },
          {
            name: "MP3Players",
            rus: "Mp3 плееры",
            eng: "MP3 players",
            uzb: "MP3 pleerlar",
          },
          {
            name: "radioTapeRecorders",
            rus: "Магнитолы",
            eng: "Radio tape recorders",
            uzb: "Radio magnitafonlari",
          },
          {
            name: "musicCenters",
            rus: "Музыкальные центры",
            eng: "Music centers",
            uzb: "Musiqa markazlari",
          },
          {
            name: "acousticSystems",
            rus: "Акустические системы",
            eng: "Acoustic systems",
            uzb: "Akustik tizimlar",
          },
          {
            name: "radioReceivers",
            rus: "Радиоприемники",
            eng: "Radio receivers",
            uzb: "Radio qabul qiluvchilar",
          },
          {
            name: "portable Acoustics",
            rus: "Портативная акустика",
            eng: "Portable acoustics",
            uzb: "Portativ akustika",
          },
          {
            name: "amplifiersReceivers",
            rus: "Усилители / ресиверы",
            eng: "Amplifiers / Receivers",
            uzb: "Kuchaytirgichlar / qabul qiluvchilar",
          },
          {
            name: "cdmdvinlyPlayers",
            rus: "Cd / md / виниловые проигрыватели",
            eng: "Cd /md / vinyl players",
            uzb: "CD / md / vinil pleyerlar",
          },
          {
            name: "otherAudioEquipment",
            rus: "Прочая аудиотехника",
            eng: "Other audio equipment",
            uzb: "Boshqa audio uskunalar",
          },
        ],
      },
      {
        name: "games",
        path: "games",
        rus: "Игры и игровые приставки",
        eng: "Games and game consoles",
        uzb: "O'yinlar va pristavkalari",
        types: [
          {
            name: "consoleGames",
            rus: "Игры для приставок",
            eng: "Console games",
            uzb: "Konsol o'yinlar",
          },
          {
            name: "gameConsoles",
            rus: "Приставки",
            eng: "Game consoles",
            uzb: "Konsollar",
          },
          {
            name: "PCGames",
            rus: "Игры для PC",
            eng: "PC games",
            uzb: "Kompyuter o'yinlari",
          },
          {
            name: "accessories",
            rus: "Аксессуары",
            eng: "Accessories",
            uzb: "Aksessuarlar",
          },
        ],
      },
      {
        name: "photoVideo",
        path: "photoAndVideo",
        rus: "Фото и Видео",
        eng: "Photo and Video",
        uzb: "Foto va Video",
        types: [
          {
            name: "filmCameras",
            rus: "Пленочные фотоаппараты",
            eng: "Film cameras",
            uzb: "Kino kameralar",
          },
          {
            name: "digitalCameras",
            rus: "Цифровые фотоаппараты",
            eng: "Digital cameras",
            uzb: "Raqamli kameralar",
          },
          {
            name: "videoCameras",
            rus: "Видеокамеры",
            eng: "Video cameras",
            uzb: "Videokameralar",
          },
          { name: "lenses", rus: "Объективы", eng: "Lenses", uzb: "Linzalar" },
          {
            name: "tripodsMonopods",
            rus: "Штативы / моноподы",
            eng: "Tripods / monopods",
            uzb: "Tripodlar / monopodlar",
          },
          {
            name: "flashlights",
            rus: "Фотовспышки",
            eng: "Flashlights",
            uzb: "Chiroqlar",
          },
          {
            name: "accessoriesForPhotoVideoCameras",
            rus: "Аксессуары для фото / видеокамер",
            eng: "Accessories for photo / video cameras",
            uzb: "Foto / video kameralar uchun aksessuarlar",
          },
          {
            name: "telescopesBinoculars",
            rus: "Телескопы / бинокли",
            eng: "Telescopes / binoculars",
            uzb: "Teleskoplar / durbinlar",
          },
        ],
      },
      {
        name: "batteriesAccumulators",
        path: "batteries",
        rus: "Батарейки, аккумуляторы",
        eng: "Batteries, accumulators",
        uzb: "Batareyalar, akkumulyatorlar",
      },
      {
        name: "individualCare",
        path: "individual-care",
        rus: "Индивидуальный уход",
        eng: "Personal care",
        uzb: "Shaxsiy g'amxo'rlik",
        types: [
          {
            name: "shaversEpilatorsClippers",
            rus: "Бритвы, эпиляторы, машинки для стрижки",
            eng: "Shavers, epilators, clippers",
            uzb: "Soch kesgichlar, epilatorlar, qaychi",
          },
          {
            name: "hairDryersHairStyling",
            rus: "Фены, укладка волос",
            eng: "Hair dryers, hair styling",
            uzb: "Soch quritgichlari, soch turmagi",
          },
          { name: "scales", rus: "Весы", eng: "Scales", uzb: "Tarozilar" },
          {
            name: "otherPersonalCareEquipment",
            rus: "Прочая техника для индивидуального ухода",
            eng: "Other personal care equipment",
            uzb: "Boshqa shaxsiy parvarish uskunalari",
          },
        ],
      },
      {
        name: "tabletsEbooksAndAccessories",
        rus: "Планшеты / эл. книги и аксессуары",
        eng: "Tablets / ebooks and accessories",
        uzb: "Planshetlar / el. kitoblar va aksessuarlar",
        types: [
          {
            name: "tabletComputers",
            rus: "Планшетные компьютеры",
            eng: "Tablet computers",
            uzb: "Planshet kompyuterlar",
          },
          {
            name: "electronicBooks",
            rus: "Электронные книги",
            eng: "Electronic books",
            uzb: "Elektron kitoblar",
          },
          {
            name: "graphicTablets",
            rus: "Графические планшеты",
            eng: "Graphic tablets",
            uzb: "Grafik planshetlar",
          },
          {
            name: "sparePartsForTabletsEbooks",
            rus: "Запчасти для планшетов / эл. книг",
            eng: "Spare parts for tablets / el. books",
            uzb: "Planshetlar uchun ehtiyot qismlar / el. kitoblar",
          },
          {
            name: "accessoriesForTabletsEbooks",
            rus: "Аксессуары для планшетов / эл. книг",
            eng: "Accessories for tablets / el. books",
            uzb: "Planshetlar uchun aksessuarlar / el. kitoblar",
          },
        ],
      },
      {
        name: "laptopsAndAccessories",
        rus: "Ноутбуки и аксессуары",
        eng: "Laptops and accessories",
        uzb: "Noutbuklar va aksessuarlar",
        types: [
          {
            name: "laptops",
            rus: "Ноутбуки",
            eng: "Laptops",
            uzb: "Noutbuklar",
          },
          {
            name: "laptopParts",
            rus: "Запчасти для ноутбуков",
            eng: "Laptop Parts",
            uzb: "Noutbuk qismlari",
          },
          {
            name: "notebookAccessories",
            rus: "Аксессуары для ноутбуков",
            eng: "Notebook accessories",
            uzb: "Noutbuk aksessuarlari",
          },
        ],
      },
      {
        name: "climaticEquipment",
        rus: "Климатическое оборудование",
        eng: "Climatic equipment",
        uzb: "Iqlim uskunalari",
      },
      {
        name: "accessoriesAndComponents",
        rus: "Аксессуары и комплектующие",
        eng: "Accessories and components",
        uzb: "Aksessuarlar va komponentlar",
      },
      {
        name: "others",
        path: "other-electronics",
        rus: "Прочая электроника",
        eng: "Other electronics",
        uzb: "Boshqa elektronikalar",
      },
    ],
  },
  {
    name: "dressesShoes",
    path: "dresses-shoes",
    rus: "Мода / Стиль",
    eng: "Clothes, shoes",
    uzb: "Kiyim, poyabzal",
    pic: dresses,
    activePic: activeDresses,
    id: 5,
    types: [
      {
        name: "womensClothing",
        path: "womens-clothing",
        rus: "Женская одежда",
        eng: "Women's clothing",
        uzb: "Ayollar kiyimi",
        types: [
          {
            name: "forWedding",
            rus: "Для свадьбы",
            eng: "For wedding",
            uzb: "To'y uchun",
          },
          {
            name: "lingerie",
            rus: "Женское белье, купальники",
            eng: "Lingerie, swimwear",
            uzb: "Ichki kiyim, suzish kiyimlari",
          },
          {
            name: "forPregnant",
            rus: "Одежда для беременных",
            eng: "Clothes for pregnant women",
            uzb: "",
          },
        ],
      },
      {
        name: "mensClothing",
        path: "mens-clothing",
        rus: "Мужская одежда",
        eng: "Men's clothing",
        uzb: "Erkaklar kiyimi",
        types: [
          {
            name: "mensUnderwearAndSwimmingTrunks",
            rus: "Мужское белье и плавки",
            eng: "Men's underwear and swimming trunks",
            uzb: "Erkaklar ichki kiyimlari va suzish kiyimlari",
          },
          {
            name: "T-shirts",
            rus: "Футболки и майки",
            eng: "T-shirts",
            uzb: "Maykalar va futbolkalar",
            types: [
              {
                name: "T-shirts",
                rus: "Футболки",
                eng: "T-shirts",
                uzb: "Futbolkalar",
              },
              {
                name: "longsleeve",
                rus: "Лонгслив",
                eng: "Longsleeve",
                uzb: "Futbolkalar",
              },
              {
                name: "undershirt",
                rus: "Майки",
                eng: "Undershirt",
                uzb: "Maykalar",
              },
              { name: "polo", rus: "Поло", eng: "Polo", uzb: "Polo" },
              { name: "other", rus: "Другие", eng: "Other", uzb: "Boshqa" },
            ],
          },
          {
            name: "ShirtsandT-shirts",
            rus: "Рубашки и тенниски",
            eng: "Shirts and T-shirts",
            uzb: "Ko'ylaklar va futbolkalar",
            types: [
              {
                name: "shirts",
                rus: "Рубашки",
                eng: "Shirts",
                uzb: "Ko'ylaklar",
              },
              {
                name: "tennisShoes",
                rus: "Тенниски",
                eng: "Tennis shoes",
                uzb: "Tennis poyabzal",
              },
              { name: "other", rus: "Другие", eng: "Other", uzb: "Boshqalar" },
            ],
          },
          {
            name: "sweaters",
            rus: "Кофты и свитеры",
            eng: "Sweaters",
            uzb: "Pidjaklar va sviterlar",
            types: [
              {
                name: "hoodie",
                rus: "Худи",
                eng: "Hoodie",
                uzb: "Qaytarma qalpoqli kiyim",
              },
              {
                name: "sweatshirt",
                rus: "Свитшот",
                eng: "Sweatshirt",
                uzb: "Sviter",
              },
              {
                name: "Hoodies",
                rus: "Толстовки",
                eng: "Hoodies",
                uzb: "Tolstovka",
              },
              {
                name: "golfTurtlenecks",
                rus: "Гольф / водолазки",
                eng: "Golf / Turtlenecks",
                uzb: "Golf / Turtlenekalar",
              },
              {
                name: "sweaters",
                rus: "Свитеры",
                eng: "Sweaters",
                uzb: "Sviterlar",
              },
              {
                name: "cardigans",
                rus: "Кардиганы",
                eng: "Cardigans",
                uzb: "Kardiganlar",
              },
              {
                name: "Sweatshirts",
                rus: "Кофты",
                eng: "Sweatshirts",
                uzb: "Koftalar",
              },
              { name: "other", rus: "Другие", eng: "Other", uzb: "Boshqa" },
            ],
          },
          {
            name: "outerwear",
            rus: "Верхняя одежда",
            eng: "Outerwear",
            uzb: "Ustki kiyim",
            types: [
              {
                name: "raincoats",
                rus: "Плащи",
                eng: "Raincoats",
                uzb: "Yomg'ir paltolari",
              },
              { name: "coat", rus: "Пальто", eng: "Coat", uzb: "Palto" },
              {
                name: "windbreakers",
                rus: "Ветровки",
                eng: "Windbreakers",
                uzb: "Vetrovka",
              },
              {
                name: "leatherJackets",
                rus: "Кожаные куртки",
                eng: "Leather jackets",
                uzb: "Teri kurtkalar",
              },
              {
                name: "jeansJackets",
                rus: "Джинсовые куртки",
                eng: "Jeans jackets",
                uzb: "Jinsili kurtkalar",
              },
              {
                name: "downJacketsAndWinterJackets",
                rus: "Пуховики и зимние куртки",
                eng: "Down jackets and winter jackets",
                uzb: "Qishki kurtkalar",
              },
              {
                name: "men'sSheepskinCoatsAndFurCoats",
                rus: "Мужские дубленки и шубы",
                eng: "Men's sheepskin coats and fur coats",
                uzb: "Dublyonka va shubalar",
              },
              { name: "vests", rus: "Жилеты", eng: "Vests", uzb: "Nimcha" },
              { name: "other", rus: "Другие", eng: "Other", uzb: "Boshqalar" },
            ],
          },
          {
            name: "shorts",
            rus: "Шорты",
            eng: "Shorts",
            uzb: "Qisqa shimlar",
          },
          {
            name: "jeans",
            rus: "Джинсы",
            eng: "Jeans",
            uzb: "Jinsilar",
          },
          {
            name: "pants",
            rus: "Брюки",
            eng: "Pants",
            uzb: "Shimlar",
            types: [
              {
                name: "joggers",
                rus: "Джоггеры",
                eng: "Joggers",
                uzb: "Joggerlar",
              },
              {
                name: "classicPants",
                rus: "Классические брюки",
                eng: "Classic pants",
                uzb: "Klassik shimlar",
              },
              { name: "other", rus: "Другие", eng: "Other", uzb: "Boshqalar" },
            ],
          },
          {
            name: "suitsAndJackets",
            rus: "Костюмы и пиджаки",
            eng: "Suits and jackets",
            uzb: "Kostyumlar va kurtkalar",
            types: [
              {
                name: "mensJackets",
                rus: "Мужские пиджаки",
                eng: "Men's jackets",
                uzb: "Erkaklar kurtkalari",
              },
              {
                name: "tuxedos",
                rus: "Смокинги",
                eng: "Tuxedos",
                uzb: "Smoking",
              },
              {
                name: "classicSuits",
                rus: "Классические костюмы",
                eng: "Classic suits",
                uzb: "Klassik kostyumlar",
              },
              { name: "other", rus: "Другие", eng: "Other", uzb: "Boshqalar" },
            ],
          },
          {
            name: "overalls",
            rus: "Комбинезоны",
            eng: "Overalls",
            uzb: "Kombinezonlar",
          },
          {
            name: "mensHomeWear",
            rus: "Мужская домашняя одежда",
            eng: "Men's home wear",
            uzb: "Erkaklar uy kiyimi",
            types: [
              { name: "pajamas", rus: "Пижамы", eng: "Pajamas", uzb: "Pijama" },
              {
                name: "bathrobes",
                rus: "Халаты",
                eng: "Bathrobes",
                uzb: "Xalatlar",
              },
              { name: "other", rus: "Другие", eng: "Other", uzb: "Boshqalar" },
            ],
          },
          {
            name: "sportswear",
            rus: "Спортивная одежда",
            eng: "Sportswear",
            uzb: "Sport kiyimi",
            types: [
              {
                name: "tracksuits",
                rus: "Спортивные костюмы",
                eng: "Tracksuits",
                uzb: "Sport kostyumlari",
              },
              {
                name: "sportJackets",
                rus: "Спортивные куртки",
                eng: "Sport jackets",
                uzb: "Sport kurtkalari",
              },
              {
                name: "sweatpants",
                rus: "Спортивные штаны",
                eng: "Sweatpants",
                uzb: "Sport shimlari",
              },
              {
                name: "SportsJerseysAndT-shirts",
                rus: "Спортивные майки и футболки",
                eng: "Sports jerseys and t-shirts",
                uzb: "Sport maykalari va futbolkalar",
              },
              {
                name: "SkiSuits",
                rus: "Лыжные комбинезоны",
                eng: "Ski suits",
                uzb: "Chang'i kostyumlari",
              },
              { name: "other", rus: "Другие", eng: "Other", uzb: "Boshqalar" },
            ],
          },
          {
            name: "mensNationalClothes",
            rus: "Мужская национальная одежда",
            eng: "Men's national clothes",
            uzb: "Erkaklar milliy kiyimlari",
            types: [
              {
                name: "mensShapan(chapan)",
                rus: "Мужской шапан (чапан)",
                eng: "Men's shapan (chapan)",
                uzb: "Erkaklar shapani (chopan)",
              },
              {
                name: "mensSkullcaps(taki)",
                rus: "Мужские тюбетейки (такии)",
                eng: "Men's skullcaps (taki)",
                uzb: "Erkaklar do'ppilari (taki)",
              },
              { name: "other", rus: "Другие", eng: "Other", uzb: "Boshqalar" },
            ],
          },
          {
            name: "muslimClothingForMen",
            rus: "Мусульманская одежда для мужчин",
            eng: "Muslim clothing for men",
            uzb: "Erkaklar uchun musulmon kiyimlari",
          },
        ],
      },
      {
        name: "childrensClothing",
        path: "childrens-clothing",
        rus: "Детская одежда, обувь",
        eng: "Children's clothing, footwear",
        uzb: "Bolalar kiyimlari, poyafzallari",
        types: [
          {
            name: "clothesForBoys",
            rus: "Одежда для мальчиков",
            eng: "Clothes for boys",
            uzb: "O'g'il bolalar uchun kiyimlar",
          },
          {
            name: "girlsClothes",
            rus: "Одежда для девочек",
            eng: "Girls clothes",
            uzb: "Qizlar kiyimlari",
          },
          {
            name: "babyClothing",
            rus: "Одежда для новорожденных",
            eng: "Baby Clothing",
            uzb: "Chaqaloq kiyimlari",
          },
          {
            name: "childrensShoes",
            rus: "Детская обувь",
            eng: "Children's shoes",
            uzb: "Bolalar poyabzali",
          },
        ],
      },
      {
        name: "shoes",
        path: "shoes",
        rus: "Обувь",
        eng: "Shoes",
        uzb: "Oyoq kiyimlari",
        types: [
          {
            name: "womensClothing",
            rus: "Женская одежда",
            eng: "Women's clothing",
            uzb: "Ayollar kiyimi",
          },
          {
            name: "mensShoes",
            rus: "Мужская обувь",
            eng: "Men's shoes",
            uzb: "Erkaklar poyabzali",
          },
        ],
      },
      {
        name: "beautyHealth",
        path: "beauty-health",
        rus: "Красота / здоровье",
        eng: "Beauty / Health",
        uzb: "Go'zallik / Sog'lik",
        types: [
          {
            name: "cosmetics",
            rus: "Косметика",
            eng: "Cosmetics",
            uzb: "Kosmetika",
          },
          {
            name: "perfumery",
            rus: "Парфюмерия",
            eng: "Perfumery",
            uzb: "Parfyumeriya",
          },
          {
            name: "careProducts",
            rus: "Средства по уходу",
            eng: "Care products",
            uzb: "G'amxo'rlik mahsulotlari",
          },
          {
            name: "other",
            rus: "Прочие товары",
            eng: "Other goods",
            uzb: "Boshqalar",
          },
        ],
      },
      {
        name: "watchesGlassesBelts",
        path: "watches-glasses-belts",
        rus: "Часы, очки, ремни",
        eng: "Watches, glasses, belts",
        uzb: "Soatlar, ko'zoynaklar, kamarlar",
        types: [
          {
            name: "watches",
            rus: "Часы",
            eng: "Watches",
            uzb: "Soatlar",
            types: [
              {
                name: "Ladies Watch",
                rus: "Женские часы",
                eng: "ladiesWatch",
                uzb: "Ayollar soati",
              },
              {
                name: "mensWatch",
                rus: "Мужские часы",
                eng: "Men's Watch",
                uzb: "Erkaklar soati",
              },
              {
                name: "sportsWatch",
                rus: "Спортивные часы",
                eng: "Sports watch",
                uzb: "Sport soati",
              },
            ],
          },
          {
            name: "glasses",
            rus: "Очки",
            eng: "Glasses",
            uzb: "Ko'zoynaklar",
          },
          {
            name: "belts",
            rus: "Ремни",
            eng: "Belts",
            uzb: "Kamarlar",
          },
        ],
      },
      {
        name: "bags",
        eng: "Bags",
        uzb: "Sumkalar",
        rus: "Сумки",
      },
      {
        name: "jewelry",
        rus: "Украшения Бижутерия",
        eng: "Jewelry Bijouterie",
        uzb: "Zargarlik bijuteriyasi",
      },
      {
        name: "overalls",
        rus: "Спецодежда",
        eng: "Overalls",
        uzb: "Kombinezonlar",
      },
      {
        name: "others",
        rus: "Разное",
        eng: "Others",
        uzb: "Boshqalar",
      },
    ],
  },
  {
    name: "building",
    path: "building",
    rus: "Строительство",
    eng: "Building",
    uzb: "Qurilish",
    pic: building,
    activePic: activeBuilding,
    id: 6,
    types: [
      {
        name: "buildingMaterials",
        path: "building-materials",
        rus: "Стройматериалы",
        eng: "Building materials",
        uzb: "Qurilish materiallari",
        type: [
          {
            name: "doorsWindowsStairsFencesLocks",
            rus: "Двери, окна, лестницы, заборы, замки",
            eng: "Doors, windows, stairs, fences, locks",
            uzb: "Eshiklar, derazalar, zinapoyalar, panjaralar, qulflar",
          },
          {
            name: "brickStonePavement",
            rus: "Кирпич, камень, брусчатка",
            eng: "Brick, stone, pavement",
            uzb: "G'isht, tosh, yulka",
          },
          {
            name: "woodMaterials",
            rus: "Материалы из дерева",
            eng: "Wood materials",
            uzb: "Yog'och materiallar",
          },
          {
            name: "decorationMaterials",
            rus: "Отделочные материалы",
            eng: "Decoration Materials",
            uzb: "Dekoratsiya materiallari",
          },
          {
            name: "sandGrantCrushedStoneBlackSoilDolomite",
            rus: "Песок, грант, щебень, чернозём, доломит",
            eng: "Sand, grant, crushed stone, black soil, dolomite",
            uzb: "Qum, grant, ezilgan tosh, qora tuproq, dolomit",
          },
          {
            name: "LEDProfilesAndStrips",
            rus: "LED профили и ленты",
            eng: "LED profiles and strips",
            uzb: "LED profillar va chiziqlar",
          },
          {
            name: "fittingsMetalStructures",
            rus: "Арматура, металлоконструкции",
            eng: "Fittings, metal structures",
            uzb: "Armatura, metall konstruktsiyalar",
          },
          {
            name: "concreteReadyMortar",
            rus: "Бетон, готовый раствор",
            eng: "Concrete, ready mortar",
            uzb: "Beton, tayyor ohak",
          },
          {
            name: "powerSuppliesDriversControllers",
            rus: "Блоки питания, драйверы, контроллеры",
            eng: "Power supplies, drivers, controllers",
            uzb: "Quvvat manbalari, drayverlar, kontrollerlar",
          },
          {
            name: "ventilation",
            rus: "Вентиляция",
            eng: "Ventilation",
            uzb: "Ventilyatsiya",
          },
          {
            name: "gutterSystem",
            rus: "Водосточная система",
            eng: "Gutter system",
            uzb: "Oluk tizimi",
          },
          {
            name: "aeratedConcreteExpandedClay",
            rus: "Газобетон, керамзит",
            eng: "Aerated concrete, expanded clay",
            uzb: "Gazlangan beton, kengaytirilgan loy",
          },
          {
            name: "waterproofingMaterials",
            rus: "Гидроизоляционные материалы",
            eng: "Waterproofing materials",
            uzb: "Gidroizolyatsiya materiallari",
          },
          {
            name: "sewerRingsPipesDrains",
            rus: "Кольца канализации, трубы, стоки",
            eng: "Sewer rings, pipes, drains",
            uzb: "Kanalizatsiya halqalari, quvurlar, drenajlar",
          },
          {
            name: "lightBulbs",
            rus: "Лампочки",
            eng: "Light bulbs",
            uzb: "Lampochka",
          },
          {
            name: "oilsChemistryMining",
            rus: "Масла, химия, отработка",
            eng: "Oils, chemistry, mining",
            uzb: "Neft, kimyo, tog'-kon sanoati",
          },
          {
            name: "metalMaterials",
            rus: "Материалы из металла",
            eng: "Metal materials",
            uzb: "Metall materiallar",
          },
          {
            name: "scrapMetal",
            rus: "Металлолом",
            eng: "Scrap metal",
            uzb: "Metall parchalari",
          },
          {
            name: "softRoof",
            rus: "Мягкая кровля",
            eng: "Soft roof",
            uzb: "Yumshoq tom",
          },
          {
            name: "floorsBeams",
            rus: "Перекрытия, балки",
            eng: "Floors, beams",
            uzb: "Zaminlar, nurlar",
          },
          {
            name: "profileForDrywall",
            rus: "Профиль для гипсокартона",
            eng: "Profile for drywall",
            uzb: "Gipsokarton uchun profil",
          },
          { name: "regips", rus: "Регипс", eng: "Regips", uzb: "Regips" },
          {
            name: "polesTowers",
            rus: "Столбы, вышки",
            eng: "Poles, towers",
            uzb: "Qutblar, minoralar",
          },
          {
            name: "heaters",
            rus: "Утеплители",
            eng: "Heaters",
            uzb: "Isitgichlar",
          },
          {
            name: "facadeMaterials",
            rus: "Фасадные материалы",
            eng: "Facade materials",
            uzb: "Fasad materiallari",
          },
          {
            name: "foundationBlocks",
            rus: "Фундаментные блоки",
            eng: "Foundation blocks",
            uzb: "Poydevor bloklari",
          },
          {
            name: "chemicalRawMaterials",
            rus: "Химическое сырье",
            eng: "Chemical raw materials",
            uzb: "Kimyoviy xom ashyo",
          },
          {
            name: "cementLime",
            rus: "Цемент, известь",
            eng: "Cement, lime",
            uzb: "Sement, ohak",
          },
          {
            name: "slateTiles",
            rus: "Шифер, черепица",
            eng: "Slate, tiles",
            uzb: "Shifer, plitka",
          },
          {
            name: "electricity",
            rus: "Электричество",
            eng: "Electricity",
            uzb: "Elektr",
          },
          { name: "other", rus: "Другое", eng: "Other", uzb: "Boshqa" },
        ],
      },
      {
        name: "toolAndTechnique",
        path: "tool-and-technique",
        rus: "Инструмент и техника",
        eng: "Tool and technique",
        uzb: "Asbob va texnika",
        types: [
          {
            name: "toolsMachinesMachinesEquipment",
            rus: "Инструмент, станки, машины, оборудование",
            eng: "Tools, machines, machines, equipment",
            uzb: "Asboblar, mashinalar, mashinalar, uskunalar",
          },
          {
            name: "constructionMachinery",
            rus: "Строительная техника",
            eng: "Construction machinery",
            uzb: "Qurilish mashinalari",
          },
          { name: "other", rus: "Другое", eng: "Other", uzb: "Boshqa" },
        ],
      },
      {
        name: "toolRental",
        path: "tool-rental",
        rus: "Аренда инструмента",
        eng: "Tool rental",
        uzb: "Asbob ijarasi",
        type: [
          {
            name: "toolRental",
            rus: "Аренда инструмента",
            eng: "Tool rental",
            uzb: "Asbob ijarasi",
          },
          {
            name: "rentSpecialEquipment",
            rus: "Аренда спецтехники",
            eng: "Rent of special equipment",
            uzb: "Maxsus jihozlarni ijaraga olish",
          },
          { name: "other", rus: "Разное", eng: "Other", uzb: "Boshqa" },
        ],
      },
      {
        name: "plumbing",
        rus: "Сантехника",
        eng: "Plumbing",
        uzb: "Santexnika",
      },
      {
        name: "gardenEquipment",
        path: "garden-equipment",
        rus: "Садовая техника",
        eng: "Garden equipment",
        uzb: "Bog' uskunalari",
        types: [
          {
            name: "aerators",
            rus: "Аэраторы",
            eng: "Aerators",
            uzb: "Aeratorlar",
          },
          {
            name: "chainsaws",
            rus: "Бензопилы",
            eng: "Chainsaws",
            uzb: "Zanjirli arralar",
          },
          {
            name: "miniTractors",
            rus: "Мини тракторы",
            eng: "Mini tractors",
            uzb: "Mini traktorlar",
          },
          {
            name: "motoblocks",
            rus: "Мотоблоки",
            eng: "Motoblocks",
            uzb: "Motobloklar",
          },
          {
            name: "electricSaws",
            rus: "Электропилы",
            eng: "Electric saws",
            uzb: "Elektr arra",
          },
          {
            name: "lawnMowers",
            rus: "Газонокосилки",
            eng: "Lawn mowers",
            uzb: "Maysa o'roq mashinalari",
          },
          {
            name: "branchShredders",
            rus: "Измельчители сучьев",
            eng: "Branch shredders",
            uzb: "Filial maydalagichlar",
          },
          {
            name: "shovelsRakes",
            rus: "Лопаты, грабли",
            eng: "Shovels, rakes",
            uzb: "Belkuraklar, tırmıklar",
          },
          {
            name: "soilCutters",
            rus: "Почвенные фрезы",
            eng: "Soil cutters",
            uzb: "Tuproq kesgichlar",
          },
          {
            name: "leafPickers",
            rus: "Сборщики листьев",
            eng: "Leaf pickers",
            uzb: "Barg yig'uvchilar",
          },
          {
            name: "snowplowsAndAggregates",
            rus: "Снегоуборочные машины и агрегаты",
            eng: "Snowplows and aggregates",
            uzb: "Qor tozalash mashinalari va agregatlar",
          },
          {
            name: "wheelbarrowsStretchers",
            rus: "Тачки, носилки",
            eng: "Wheelbarrows, stretchers",
            uzb: "G'ildiraklar, zambillar",
          },
          {
            name: "trimmers",
            rus: "Триммеры",
            eng: "Trimmers",
            uzb: "Trimmerlar",
          },
          {
            name: "tapestryScissors",
            rus: "Шпалерные ножницы",
            eng: "Tapestry scissors",
            uzb: "Gobelen qaychi",
          },
          { name: "tape", rus: "Плёнка", eng: "Tape", uzb: "Lenta" },
          {
            name: "greenhouses",
            rus: "Теплицы",
            eng: "Greenhouses",
            uzb: "Issiqxonalar",
          },
          {
            name: "gardenFurnitureAndAccessories",
            rus: "Садовая мебель и аксессуары",
            eng: "Garden furniture and accessories",
            uzb: "Bog' mebellari va aksessuarlari",
          },
          {
            name: "agriculturalMachinery",
            rus: "Сельско-хозяйственная техника",
            eng: "Agricultural machinery",
            uzb: "Qishloq xo'jaligi texnikasi",
          },
          { name: "other", rus: "Разное", eng: "Other", uzb: "Boshqa" },
        ],
      },
      {
        name: "projectsDesign",
        path: "projects-design",
        rus: "Проекты, дизайн",
        eng: "Projects, design",
        uzb: "Loyihalar, dizayn",
        types: [
          {
            name: "architecturalProjectsPlans",
            rus: "Архитектурные проекты, планы",
            eng: "Architectural projects, plans",
            uzb: "Arxitektura loyihalari, rejalari",
          },
          {
            name: "aerialPhotographyOfTheAreaAndObjects",
            rus: "Аэрофотосьемка местности и обьектов",
            eng: "Aerial photography of the area and objects",
            uzb: "Hudud va ob'ektlarni aerofotosuratga olish",
          },
          {
            name: "geologicalSurveysSurveyors",
            rus: "Геологические исследования, землемеры",
            eng: "Geological surveys, surveyors",
            uzb: "Geologik tadqiqotlar, geodeziyachilar",
          },
          {
            name: "interiorAndPlotDesign",
            rus: "Дизайн интерьеров и участков",
            eng: "Interior and plot design",
            uzb: "Interer va uchastka dizayni",
          },
          { name: "other", rus: "Разное", eng: "Other", uzb: "Boshqa" },
        ],
      },
      {
        name: "transportationAndLoading",
        path: "transportation-and-loading",
        rus: "Перевозка и погрузка",
        eng: "Transportation and loading",
        uzb: "Tashish va yuklash",
        types: [
          {
            name: "passengerTransportation",
            rus: "Пассажирские перевозки",
            eng: "Passenger Transportation",
            uzb: "Yo'lovchi tashish",
          },
          {
            name: "appliances",
            rus: "Бытовая техника",
            eng: "Appliances",
            uzb: "Maishiy texnika",
          },
          {
            name: "deliveryOfFragileAndDelicateGoods",
            rus: "Доставка хрупких и деликатных грузов",
            eng: "Delivery of fragile and delicate goods",
            uzb: "Nozik tovarlarni yetkazib berish",
          },
          {
            name: "railTransportation",
            rus: "Железнодорожные перевозки",
            eng: "Rail transportation",
            uzb: "Temir yo'l transporti",
          },
          {
            name: "liquidCargo",
            rus: "Жидкие грузы",
            eng: "Liquid cargo",
            uzb: "Suyuq yuk",
          },
          {
            name: "oversizedCargoTransportation",
            rus: "Крупногабаритные грузоперевозки",
            eng: "Oversized cargo transportation",
            uzb: "Katta o'lchamdagi yuklarni tashish",
          },
          {
            name: "expressDelivery",
            rus: "Курьерская доставка",
            eng: "Express delivery",
            uzb: "Ekspress yetkazib berish",
          },
          {
            name: "internationalTransportTIR",
            rus: "Международные перевозки TIR",
            eng: "International transport TIR",
            uzb: "Xalqaro transport TIR",
          },
          {
            name: "waterCargo",
            rus: "Морские перевозки",
            eng: "Water cargo",
            uzb: "Suv transportida yetkazib berish",
          },
          {
            name: "dangerousAndFlammableGoods",
            rus: "Опасные и горючие грузы",
            eng: "Dangerous and flammable goods",
            uzb: "Yonuvchan va xavfli mahsulotlar",
          },
          {
            name: "transportationAndLoadingOfTimber",
            rus: "Перевозка и погрузка леса",
            eng: "Transportation and loading of timber",
            uzb: "Yog'ochni tashish va yuklash",
          },
          {
            name: "furnitureTransportation",
            rus: "Перевозка мебели",
            eng: "Furniture transportation",
            uzb: "Mebel tashish",
          },
          {
            name: "buildingMaterialsAndStructures",
            rus: "Стройматериалы и конструкции",
            eng: "Building materials and structures",
            uzb: "Qurilish materiallari va inshootlari",
          },
          {
            name: "bulkCargo",
            rus: "Сыпучие грузы",
            eng: "Bulk cargo",
            uzb: "Ommaviy yuk",
          },
          {
            name: "animalTransportation",
            rus: "Транспортировка животных",
            eng: "Animal transportation",
            uzb: "Hayvonlarni tashish",
          },
          {
            name: "airTransportation",
            rus: "Авиа перевозки",
            eng: "Air transportation",
            uzb: "Havo transporti",
          },
          {
            name: "carEvacuation",
            rus: "Автоэвакуация",
            eng: "Car evacuation",
            uzb: "Avtomobilni evakuatsiya qilish",
          },
          {
            name: "householdWasteRemoval",
            rus: "Вывоз бытового мусора",
            eng: "Household waste removal",
            uzb: "Maishiy chiqindilarni olib tashlash",
          },
          {
            name: "garbageCollectionInContainers",
            rus: "Вывоз мусора ( в контейнерах )",
            eng: "Garbage collection (in containers)",
            uzb: "Axlat yig'ish (konteynerlarda)",
          },
          {
            name: "removalOfSnowAndLeaves",
            rus: "Вывоз снега и листьев",
            eng: "Removal of snow and leaves",
            uzb: "Qor va barglarni olib tashlash",
          },
          {
            name: "wastePitCleaning",
            rus: "Очистка сточных ям",
            eng: "Waste pit cleaning",
            uzb: "Chiqindilarni tozalash",
          },
          {
            name: "logistics",
            rus: "Логистика",
            eng: "Logistics",
            uzb: "Logistika",
          },
          { name: "other", rus: "Другое", eng: "Other", uzb: "Boshqa" },
        ],
      },
    ],
  },
  {
    name: "forHome",
    path: "for-home",
    rus: "Для дома",
    eng: "For home",
    uzb: "Uy uchun",
    pic: home,
    activePic: activeHome,
    id: 7,
    types: [
      {
        name: "furnitureInterior",
        path: "furniture-interior",
        rus: "Мебель, интерьер",
        eng: "Furniture, interior",
        uzb: "Mebel, interyer",
        types: [
          {
            name: "forApartment",
            rus: "Для квартиры",
            eng: "For apartment",
            uzb: "Kvartira uchun",
          },
          {
            name: "forOffice",
            rus: "Для офиса",
            eng: "For office",
            uzb: "Ofis uchun",
          },
          {
            name: "customMadeFurniture",
            rus: "Мебель на заказ",
            eng: "Custom-made furniture",
            uzb: "Buyurtma asosida mebel",
          },
          {
            name: "gardenFurniture",
            rus: "Садовая мебель",
            eng: "garden furniture",
            uzb: "Bog' mebellari",
          },
          {
            name: "specializedFurniture",
            rus: "Специализированная мебель",
            eng: "Specialized furniture",
            uzb: "Maxsus mebel",
          },
        ],
      },
      {
        name: "handMadeProducts",
        rus: "Изделия ручной работы",
        eng: "Hand-made products",
        uzb: "Qo'lda tayyorlangan mahsulotlar",
      },
      {
        name: "antiquesPaintings",
        rus: "Антиквариат, картины",
        eng: "Antiques, paintings",
        uzb: "Antikvar buyumlar, rasmlar",
      },
      {
        name: "housePlants",
        rus: "Домашние растения",
        eng: "House plants",
        uzb: "Uy o'simliklari",
      },
      {
        name: "other",
        eng: "Others",
        uzb: "Boshqalar",
        rus: "Другое",
      },
    ],
  },
  {
    name: "gifts",
    rus: "Подарки",
    eng: "Gifts",
    uzb: "Sovg'alar",
    pic: gifts,
    activePic: activeGifts,
    path: "gifts",
    id: 13,
    types: [
      {
        name: "forWomen",
        rus: "Для женщины",
        eng: "For women",
        uzb: "Qizlar uchun",
      },
      {
        name: "forMen",
        rus: "Для мужчины",
        eng: "For men",
        uzb: "Erkaklar uchun",
      },
      {
        name: "paired",
        rus: "Парное",
        eng: "Paired",
        uzb: "Juftlik uchun",
      },
      {
        name: "forChildren",
        rus: "Для ребёнка",
        eng: "For children",
        uzb: "Bolalar uchun",
      },
      {
        name: "certificates",
        rus: "Сертификаты",
        eng: "Certificates",
        uzb: "Sertifikatlar",
      },
    ],
  },
  {
    name: "forChildren",
    rus: "Для детей",
    eng: "For children",
    uzb: "Bolalar uchun",
    pic: children,
    activePic: activeChildren,
    id: 9,
    types: [
      {
        name: "strollers",
        rus: "Коляски",
        eng: "Strollers",
        uzb: "Aravachalar",
      },
      {
        name: "carSeatsCarriers",
        rus: "Автокресла, переноски",
        eng: "Car seats, carriers",
        uzb: "Avtomobil o'rindiqlari, tashuvchilar",
      },
      {
        name: "childrensFurniture",
        rus: "Детская мебель",
        eng: "Children's furniture",
        uzb: "Bolalar mebeli",
      },
      {
        name: "toysSwing",
        rus: "Игрушки, качели",
        eng: "Toys, swing",
        uzb: "O'yinchoqlar, belanchak",
      },
      {
        name: "accessoriesAndNutrition",
        eng: "Accessories and nutrition",
        rus: "Аксессуары и питание",
        uzb: "Aksessuarlar va ovqatlanish",
      },
      {
        name: "circlesKindergartensSections",
        rus: "Кружки, садики, секции",
        eng: "Circles, kindergartens, sections",
        uzb: "To'garaklar, bolalar bog'chalari, bo'limlar",
      },
      {
        name: "childrensActivities",
        rus: "Детские мероприятия",
        eng: "Children's activities",
        uzb: "Bolalar faoliyati",
      },
      {
        name: "everythingForSchool",
        rus: "Все для школы",
        eng: "Everything for school",
        uzb: "Maktab uchun hamma narsa",
      },
      {
        name: "others",
        rus: "Разное",
        eng: "Others",
        uzb: "Boshqalar",
      },
    ],
  },
  {
    name: "animals",
    path: "animals",
    rus: "Животные",
    eng: "Animals",
    uzb: "Hayvonlar",
    pic: animals,
    activePic: activeAnimals,
    id: 10,
    types: [
      {
        name: "zooProducts",
        rus: "Зоотовары",
        eng: "Zoo products",
        uzb: "Hayvonot bog'i mahsulotlari",
      },
      {
        name: "dogsPuppies",
        rus: "Собаки, щенки",
        eng: "Dogs, puppies",
        uzb: "Itlar, kuchuklar",
      },
      {
        name: "catsKittens",
        rus: "Кошки, котята",
        eng: "Cats, kittens",
        uzb: "Mushuklar, mushukchalar",
      },
      {
        name: "rodents",
        rus: "Грызуны",
        eng: "Rodents",
        uzb: "Kemiruvchilar",
      },
      {
        name: "parrotsAndBirds",
        rus: "Попугаи и птицы",
        eng: "Parrots and birds",
        uzb: "To'tiqushlar va qushlar",
      },
      {
        name: "fishAquariums",
        rus: "Рыбки, аквариумы",
        eng: "Fish, aquariums",
        uzb: "Baliqlar, akvariumlar",
      },
      {
        name: "Exotic animals",
        rus: "Экзотические животные",
        eng: "Exotic animals",
        uzb: "Ekzotik hayvonlar",
      },
      {
        name: "farmAnimals",
        rus: "Сельхоз животные",
        eng: "Farm animals",
        uzb: "Ferma hayvonlari",
      },
      {
        name: "veterinary",
        rus: "Ветеринария",
        eng: "Veterinary",
        uzb: "Veterinariya",
      },
      {
        name: "searchesFinds",
        rus: "Поиски, находки",
        eng: "Searches, finds",
        uzb: "Qidiruv, topilmalar",
      },
      {
        name: "other",
        rus: "Разное",
        eng: "Others",
        uzb: "Boshqalar",
      },
    ],
  },
  {
    name: "agriculture",
    path: "agriculture",
    rus: "Сельское хозяйство",
    eng: "Agriculture",
    uzb: "Qishloq xo'jaligi",
    pic: agriculture,
    activePic: activeAgriculture,
    id: 11,
    types: [
      {
        name: "agricuturalWork",
        rus: "Сельхозработы",
        eng: "Agricultural work",
        uzb: "Qishloq xo'jaligi ishi",
      },
      {
        name: "vegetableHorticulture",
        rus: "Овощеводство / садоводство",
        eng: "Vegetable / horticulture",
        uzb: "Sabzavot / bog'dorchilik",
      },
      {
        name: "fertilizersAndChemicals",
        rus: "Удобрения и химикаты",
        eng: "Fertilizers and chemicals",
        uzb: "O'g'itlar va kimyoviy moddalar",
      },
      {
        name: "seedsAndSeedlings",
        rus: "Семена и рассада",
        eng: "Seeds and seedlings",
        uzb: "Urug'lar va ko'chatlar",
      },
      {
        name: "others",
        rus: "Разное",
        eng: "Others",
        uzb: "Boshqalar",
      },
    ],
  },
  {
    name: "leisureHobbies",
    path: "entertainment-holiday",
    rus: "Отдых увлечения",
    eng: "Leisure hobbies",
    uzb: "Sevimli mashg'ulotlar",
    pic: holiday,
    activePic: activeHoliday,
    id: 12,
    types: [
      {
        name: "hobbies",
        rus: "Хобби, увлечения",
        eng: "Hobbies",
        uzb: "Sevimli mashg'ulotlar",
      },
      {
        name: "collecting",
        rus: "Коллекционирование",
        eng: "Collecting",
        uzb: "Yig'ish",
      },
      {
        name: "ticketsConcertsWhereToGo",
        rus: "Билеты, концерты, куда пойти",
        eng: "Tickets, concerts, where to go",
        uzb: "Chiptalar, konsertlar, qaerga borish",
      },
      {
        name: "musicInstrumentsLearning",
        rus: "Музыка, инструменты, обучение",
        eng: "Music, instruments, learning",
        uzb: "Musiqa, asboblar, o'rganish",
      },
      {
        name: "books",
        rus: "Книги",
        eng: "Books",
        uzb: "Kitoblar",
      },
      {
        name: "sportsActiveRecreation",
        rus: "Спорт, активный отдых",
        eng: "Sports, active recreation",
        uzb: "Sport, faol dam olish",
      },
      {
        name: "huntingFishing",
        rus: "Охота, рыбалка",
        eng: "Hunting Fishing",
        uzb: "Ovchilik Baliq ovlash",
      },
      {
        name: "tourism",
        rus: "Туризм",
        eng: "Tourism",
        uzb: "Turizm",
      },
      {
        name: "others",
        eng: "Others",
        uzb: "Boshqalar",
        rus: "Всё остальное",
      },
    ],
  },
  {
    name: "services",
    path: "services",
    rus: "Сервисы",
    eng: "Services",
    uzb: "Xizmatlar",
    pic: services,
    activePic: activeServices,
    id: 8,
    types: [
      {
        name: "constructionRenovationCleaning",
        rus: "Строительство / ремонт / уборка",
        eng: "Construction / renovation / cleaning",
        uzb: "Qurilish / ta'mirlash / tozalash",
      },
      {
        name: "advertisingPrintingMarketingInternet",
        rus: "Реклама / полиграфия / маркетинг / интернет",
        eng: "Advertising / printing / marketing / internet",
        uzb: "Reklama / matbaa / marketing / internet",
      },
      {
        name: "babysittersNurses",
        rus: "Няни / сиделки",
        eng: "Babysitters / nurses",
        uzb: "Enagalar / hamshiralar",
      },
      {
        name: "transportationAndLoading",
        rus: "Перевозка и погрузка",
        eng: "Transportation and loading",
        uzb: "Tashish va yuklash",
      },
      {
        name: "rawMaterialsMaterials",
        rus: "Сырьё / материалы",
        eng: "Raw materials / materials",
        uzb: "Xom ashyo / materiallar",
      },
      {
        name: "beautyHealth",
        rus: "Красота / здоровье",
        eng: "Beauty / health",
        uzb: "Go'zallik / salomatlik",
      },
      {
        name: "education",
        rus: "Образование",
        eng: "Education",
        uzb: "Ta'lim",
      },
      {
        name: "servicesForAnimals",
        rus: "Услуги для животных",
        eng: "Services for animals",
        uzb: "Hayvonlar uchun xizmatlar",
      },
      {
        name: "entertainmentArtPhotoVideo",
        rus: "Развлечения / Искусство / Фото / Видео",
        eng: "Entertainment / Art / Photo / Video",
        uzb: "Ko'ngilochar / San'at / Foto / Video",
      },
      {
        name: "autoMotoServices",
        rus: "Авто / мото услуги",
        eng: "Auto / moto services",
        uzb: "Avto/moto xizmatlari",
      },
      {
        name: "equipmentRepair",
        rus: "Ремонт техники",
        eng: "Equipment repair",
        uzb: "Uskunalarni ta'mirlash",
      },
      {
        name: "goodsRental",
        rus: "Прокат товаров",
        eng: "Goods rental",
        uzb: "Tovarlarni ijaraga berish",
      },
      {
        name: "businessSale",
        rus: "Продажа бизнеса",
        eng: "Business sale",
        uzb: "Biznes sotish",
      },
      {
        name: "other",
        rus: "Прочие услуги",
        eng: "Other services",
        uzb: "Boshqa xizmatlar",
      },
    ],
  },
  {
    name: "providers",
    path: "providers",
    rus: "Поставщики",
    eng: "Providers",
    uzb: "Yetkazib beruvchilar",
    pic: providers,
    activePic: activeProviders,
    id: 14,
    types: [
      {
        name: "wholesale",
        rus: "Оптовые продажи",
        eng: "Wholesale",
        uzb: "Ulgurji savdo",
      },
      {
        name: "forConstruction",
        rus: "Для строительства",
        eng: "For construction",
        uzb: "Qurilish uchun",
      },
      {
        name: "forAnimals",
        eng: "For animals",
        uzb: "Hayvonlar uchun",
        rus: "Для животных",
      },
      {
        name: "forClothes",
        rus: "Для одежды",
        eng: "For clothes",
        uzb: "Kiyim uchun",
      },
      {
        name: "electronics",
        rus: "Электротехника",
        eng: "Electronics",
        uzb: "Elektronika",
      },
      {
        name: "furniture",
        rus: "Мебель",
        eng: "Furniture",
        uzb: "Mebel",
      },
      {
        name: "plumbing",
        rus: "Сантехника",
        eng: "Plumbing",
        uzb: "Santexnika",
      },
      {
        name: "others",
        eng: "Others",
        uzb: "Boshqalar",
        rus: "Другое",
      },
    ],
  },
];
