import work from "../../assets/work.png";
import activeWork from "../../assets/work-active.png";
import transport from "../../assets/transport.png";
import activeTransport from "../../assets/transport-active.png";
import estate from "../../assets/estate.png";
import activeEstate from "../../assets/estate-active.png";
import electronics from "../../assets/electrical-devices.png";
import activeElectronics from "../../assets/electrical-devices-active.png";
import dresses from "../../assets/dresses.png";
import activeDresses from "../../assets/dresses-active.png";
import building from "../../assets/building.png";
import activeBuilding from "../../assets/building-active.png";
import home from "../../assets/home.png";
import activeHome from "../../assets/home-active.png";
import services from "../../assets/services.png";
import activeServices from "../../assets/services-active.png";
import children from "../../assets/children.png";
import activeChildren from "../../assets/children-active.png";
import animals from "../../assets/animals.png";
import activeAnimals from "../../assets/animals-active.png";
import agriculture from "../../assets/agriculture.png";
import activeAgriculture from "../../assets/agriculture-active.png";
import holiday from "../../assets/holiday.png";
import activeHoliday from "../../assets/holiday-active.png";
import gifts from "../../assets/gifts.png";
import activeGifts from "../../assets/gifts-active.png";
import providers from "../../assets/provider.png";
import activeProviders from "../../assets/provider-active.png";

export const categories = [
  {
    name: "workAndBusiness",
    rus: "Работа и бизнес",
    eng: "Work and business",
    uzb: "Ish va biznes",
    pic: work,
    activePic: activeWork,
    path: "work-and-business",
    id: 1,
    types: [
      {
        name: "vacancies",
        path: "vacancies",
        rus: "Вакансии",
        eng: "Vacancies",
        uzb: "Bo'sh ish o'rinlari",
        types: [
          {
            name: "retail",
            path: "retail",
            rus: "Розничная торговля / Продажи",
            eng: "Retail / Sales",
            uzb: "Chakana savdo / sotish",
            types: [
              { name: "", path: "", rus: "Продавец", eng: "", uz: "" },
              {
                name: "",
                path: "",
                rus: "Продавец консультант",
                eng: "",
                uz: "",
              },
              {
                name: "",
                path: "",
                rus: "Торговый представитель",
                eng: "",
                uz: "",
              },
              {
                name: "",
                path: "",
                rus: "Менеджер по продажам",
                eng: "",
                uz: "",
              },
              { name: "", path: "", rus: "Мерчандайзер", eng: "", uz: "" },
              { name: "", path: "", rus: "Кассир", eng: "", uz: "" },
              { name: "", path: "", rus: "Флорист", eng: "", uz: "" },
              {
                name: "",
                path: "",
                rus: "Администратор магазина / торгового зала",
                eng: "",
                uz: "",
              },
              {
                name: "",
                path: "",
                rus: "Менеджер по снабжению",
                eng: "",
                uz: "",
              },
              {
                name: "",
                path: "",
                rus: "Менеджер интернет-магазина",
                eng: "",
                uz: "",
              },
              { name: "", path: "", rus: "Другое", eng: "", uz: "" },
            ],
          },
          {
            name: "transport",
            path: "transport",
            rus: "Транспорт / логистика",
            eng: "Transport / logistics",
            uzb: "Transport / logistika",
            types: [
              { name: "", path: "", rus: "Водитель", eng: "", uz: "" },
              { name: "", path: "", rus: "Курьер", eng: "", uz: "" },
              { name: "", path: "", rus: "Грузчик", eng: "", uz: "" },
              { name: "", path: "", rus: "Экспедитор", eng: "", uz: "" },
              { name: "", path: "", rus: "Машинист", eng: "", uz: "" },
              { name: "", path: "", rus: "Дальнобойщик", eng: "", uz: "" },
              { name: "", path: "", rus: "Логист", eng: "", uz: "" },
              { name: "", path: "", rus: "Комплектовщик", eng: "", uz: "" },
              { name: "", path: "", rus: "Диспетчер", eng: "", uz: "" },
              { name: "", path: "", rus: "Работа в такси", eng: "", uz: "" },
              { name: "", path: "", rus: "Другое", eng: "", uz: "" },
            ],
          },
          {
            name: "building",
            path: "building",
            rus: "Строительство",
            eng: "Building",
            uzb: "Qurilish",
            types: [
              { name: "", path: "", rus: "Разнорабочий", eng: "", uz: "" },
              { name: "", path: "", rus: "Сварщик", eng: "", uz: "" },
              {
                name: "",
                path: "",
                rus: "Монтажник / Установщик",
                eng: "",
                uz: "",
              },
              { name: "", path: "", rus: "Электромонтажник", eng: "", uz: "" },
              { name: "", path: "", rus: "Сантехник", eng: "", uz: "" },
              { name: "", path: "", rus: "Электрик", eng: "", uz: "" },
              { name: "", path: "", rus: "Каменщик", eng: "", uz: "" },
              { name: "", path: "", rus: "Слесарь", eng: "", uz: "" },
              { name: "", path: "", rus: "Плотник", eng: "", uz: "" },
              { name: "", path: "", rus: "Маляр", eng: "", uz: "" },
              { name: "", path: "", rus: "Прораб", eng: "", uz: "" },
              { name: "", path: "", rus: "Бетонщик", eng: "", uz: "" },
              { name: "", path: "", rus: "Арматурщик", eng: "", uz: "" },
              { name: "", path: "", rus: "Машинист", eng: "", uz: "" },
              { name: "", path: "", rus: "Штукатур", eng: "", uz: "" },
              { name: "", path: "", rus: "Геодезист", eng: "", uz: "" },
              {
                name: "",
                path: "",
                rus: "Дизайнер интерьера",
                eng: "",
                uz: "",
              },
              { name: "", path: "", rus: "Машинист крана", eng: "", uz: "" },
              { name: "", path: "", rus: "Проектировщик", eng: "", uz: "" },
              {
                name: "",
                path: "",
                rus: "Промышленный альпинист",
                eng: "",
                uz: "",
              },
              { name: "", path: "", rus: "Сметчик", eng: "", uz: "" },
              { name: "", path: "", rus: "Архитектор", eng: "", uz: "" },
              {
                name: "",
                path: "",
                rus: "Строительство дорог",
                eng: "",
                uz: "",
              },
              { name: "", path: "", rus: "Другое", eng: "", uz: "" },
            ],
          },
          {
            name: "restaurants",
            path: "restaurants",
            rus: "Бары / рестораны",
            eng: "Bar/Restaurant",
            uzb: "Bar/restoran",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "jurisdiction",
            path: "jurisdiction",
            rus: "Юриспруденция и бухгалтерия",
            eng: "Jurisprudence and accounting",
            uzb: "Huquq va buxgalteriya hisobi",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "security",
            path: "security",
            rus: "Охрана / безопасность",
            eng: "Security / security",
            uzb: "Xavfsizlik / xavfsizlik",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "housePersonnel",
            path: "housePersonnel",
            rus: "Домашний персонал",
            eng: "Household staff",
            uzb: "Uy xodimlari",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "beautyFitnessSport",
            path: "beautyFitnessSport",
            rus: "Красота / фитнес / спорт",
            eng: "Beauty / fitness / sports",
            uzb: "Go'zallik / fitnes / sport",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "tourism",
            path: "tourism",
            rus: "Туризм / отдых / развлечения",
            eng: "Tourism / Leisure / Entertainment",
            uzb: "Turizm / Dam olish / O'yin-kulgi",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "education",
            path: "education",
            rus: "Образование",
            eng: "Education",
            uzb: "Ta'lim",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "culture",
            path: "culture",
            rus: "Культура / искусство",
            eng: "Culture / art",
            uzb: "Madaniyat / san'at",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "medicine",
            path: "medicine",
            rus: "Медицина / фармация",
            eng: "Medicine / Pharmacy",
            uzb: "Tibbiyot / Dorixona",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "it",
            path: "it",
            rus: "ИТ / телеком / компьютеры",
            eng: "IT / telecom / computers",
            uzb: "IT / telekom / kompyuterlar",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "realEstate",
            path: "realEstate",
            rus: "Недвижимость",
            eng: "Real estate",
            uzb: "Ko `chmas mulk",
            types: [
              { name: "", path: "", rus: "Риэлтор", eng: "", uz: "" },
              {
                name: "",
                path: "",
                rus: "Менеджер по продажам недвижимости",
                eng: "",
                uz: "",
              },
              { name: "", path: "", rus: "Другое", eng: "", uz: "" },
            ],
          },
          {
            name: "marketing",
            path: "marketing",
            rus: "Маркетинг / реклама / дизайн",
            eng: "Marketing / advertising / design",
            uzb: "Marketing / reklama / dizayn",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "manufacture",
            path: "manufacture",
            rus: "Производство / энергетика",
            eng: "Manufacturing / energy",
            uzb: "Ishlab chiqarish / energiya",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "secretarian",
            path: "secretarian",
            rus: "Cекретариат / АХО",
            eng: "Secretariat / AHO",
            uzb: "Kotibiyat / AHO",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "students",
            path: "students",
            rus: "Начало карьеры / Студенты",
            eng: "Career start / Students",
            uzb: "Karyera boshlanishi / Talabalar",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "services",
            path: "services",
            rus: "Сервис и быт",
            eng: "Service and life",
            uzb: "Xizmat va hayot",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "otherOccupations",
            path: "others-occupations",
            rus: "Другие сферы занятий",
            eng: "Other occupations",
            uzb: "Boshqa kasblar",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "partTime",
            path: "part-time",
            rus: "Частичная занятость",
            eng: "Part-time employment",
            uzb: "Yarim kunlik ish",
            types: [
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
              { name: "", path: "", rus: "", eng: "", uz: "" },
            ],
          },
          {
            name: "otherWorks",
            rus: "разное",
            eng: "Others",
            uzb: "Boshqalar",
            path: "other-work",
          },
        ],
      },
      { name: "", rus: "Ищут работу", eng: "", uzb: "", path: "" },
      { name: "", rus: "Курсы, образование", eng: "", uzb: "", path: "" },
      { name: "", rus: "Юридические услуги", eng: "", uzb: "", path: "" },
      { name: "", rus: "Финансовые услуги", eng: "", uzb: "", path: "" },
      { name: "", rus: "Интернет-услуги", eng: "", uzb: "", path: "" },
      { name: "", rus: "Разное", eng: "", uzb: "", path: "" },
    ],
  },
  {
    name: "transport",
    path: "transport",
    rus: "Транспорт",
    eng: "Transport",
    uzb: "Transport",
    pic: transport,
    activePic: activeTransport,
    id: 2,
    types: [
      {
        name: "cars",
        path: "cars",
        rus: "Легковые авто",
        eng: "Cars",
        uzb: "Yengil mashinalar",
        types: [
          { rus: "Chevrolet" },
          { rus: "Audi" },
          { rus: "Baic" },
          { rus: "BMW" },
          { rus: "BYD" },
          { rus: "Daewoo" },
          { rus: "Denza" },
          { rus: "Fiat" },
          { rus: "Ford" },
          { rus: "GAC" },
          { rus: "Haval" },
          { rus: "Hyundai" },
          { rus: "Isuzu" },
          { rus: "JAC" },
          { rus: "Kia" },
          { rus: "Lexus" },
          { rus: "Mazda" },
          { rus: "Mercedes" },
          { rus: "Mitsubishi" },
          { rus: "Nio" },
          { rus: "Nissan" },
          { rus: "Opel" },
          { rus: "ORA" },
          { rus: "Peugeot" },
          { rus: "Porsche" },
          { rus: "Skoda" },
          { rus: "Tesla" },
          { rus: "Toyota" },
          { rus: "Volkswagen" },
          { rus: "Xpeng" },
          { rus: "ВАЗ" },
          { rus: "ГАЗ" },
          { rus: "ЗАЗ" },
          { rus: "ИЖ" },
          { rus: "Москвич" },
          { rus: "УАЗ" },
          { rus: "others" },
        ],
      },
      {
        name: "trucks",
        path: "trucks",
        rus: "Грузовые машины",
        eng: "Trucks",
        uzb: "Yuk mashinalar",
      },
      {
        name: "moto",
        path: "moto",
        rus: "Мото транспорт",
        eng: "Motorcycle transport",
        uzb: "Mototsikl transporti",
        types: [
          { name: "", rus: "Мопеды / скутеры", eng: "", uzb: "" },
          { name: "", rus: "Квадроциклы", eng: "", uzb: "" },
          { name: "", rus: "Мотоциклы", eng: "", uzb: "" },
          { name: "", rus: "Мото - прочее", eng: "", uzb: "" },
        ],
      },
      {
        name: "bikes",
        path: "bikes",
        rus: "Велосипеды, самокаты",
        eng: "Bicycles, scooters",
        uzb: "Velosipedlar, skuterlar",
      },

      {
        name: "repairAndSpareParts",
        path: "repair-and-spare-parts",
        rus: "Запчасти для авто и мото",
        eng: "Repair and spare parts",
        uzb: "Ta'mirlash va ehtiyot qismlar",
        carSpares: [
          { name: "", rus: "Автозапчасти", eng: "", uzb: "" },
          { name: "", rus: "Аксессуары для авто", eng: "", uzb: "" },
          { name: "", rus: "Автозвук", eng: "", uzb: "" },
          { name: "", rus: "Транспорт на запчасти", eng: "", uzb: "" },
          {
            name: "",
            rus: "GPS-навигаторы / авторегистраторы",
            eng: "",
            uzb: "",
          },
        ],
        motoSpares: [
          { name: "", rus: "Мотозапчасти", eng: "", uzb: "" },
          { name: "", rus: "Мотоэкипировка", eng: "", uzb: "" },
          { name: "", rus: "Мото аксессуары", eng: "", uzb: "" },
        ],
        tiresWheels: [
          { name: "", rus: "Автошины", eng: "", uzb: "" },
          { name: "", rus: "Мотошины", eng: "", uzb: "" },
          { name: "", rus: "Диски", eng: "", uzb: "" },
          { name: "", rus: "Колеса в сборе", eng: "", uzb: "" },
          { name: "", rus: "Колпаки", eng: "", uzb: "" },
        ],
      },
      {
        name: "cargoTransportation",
        path: "cargo-transportation",
        rus: "Перевозка грузов",
        eng: "Cargo transportation",
        uzb: "Yuk tashish",
        types: [
          {
            name: "",
            rus: "Пассажирские перевозки",
            eng: "Passenger transportation",
            uzb: "",
          },
          {
            name: "",
            rus: "Бытовая техника, вещи",
            eng: "Household appliances, things",
            uzb: "",
          },
          {
            name: "",
            rus: "Доставка хрупких и деликатных грузов",
            eng: "Delivery of fragile and delicate goods",
            uzb: "",
          },
          {
            name: "",
            rus: "Железнодорожные перевозки",
            eng: "Rail transportation",
            uzb: "",
          },
          { name: "", rus: "Жидкие грузы", eng: "Liquid cargo", uzb: "" },
          {
            name: "",
            rus: "Крупногабаритные грузоперевозки",
            eng: "Oversized cargo transportation",
            uzb: "",
          },
          {
            name: "",
            rus: "Курьерская доставка",
            eng: "Courier delivery",
            uzb: "",
          },
          {
            name: "",
            rus: "Международные перевозки TIR",
            eng: "International transport TIR",
            uzb: "",
          },
          {
            name: "",
            rus: "Опасные и горючие грузы",
            eng: "Dangerous and flammable goods",
            uzb: "",
          },
          {
            name: "",
            rus: "Перевозка и погрузка леса",
            eng: "Transportation and loading of timber",
            uzb: "",
          },
          {
            name: "",
            rus: "Перевозка мебели",
            eng: "Transportation of furniture",
            uzb: "",
          },
          {
            name: "",
            rus: "Стройматериалы и конструкции",
            eng: "Building materials and structures",
            uzb: "",
          },
          { name: "", rus: "Сыпучие грузы", eng: "Bulk cargo", uzb: "" },
          {
            name: "",
            rus: "Транспортировка животных",
            eng: "Animal transportation",
            uzb: "",
          },
          {
            name: "",
            rus: "Авиа перевозки",
            eng: "Air transportation",
            uzb: "",
          },
          { name: "", rus: "Автоэвакуация", eng: "Car evacuation", uzb: "" },
          {
            name: "",
            rus: "Вывоз бытового мусора",
            eng: "Household waste removal",
            uzb: "",
          },
          {
            name: "",
            rus: "Вывоз мусора ( в контейнерах )",
            eng: "Garbage collection ( in containers )",
            uzb: "",
          },
          {
            name: "",
            rus: "Вывоз снега и листьев",
            eng: "Snow and leaf removal",
            uzb: "",
          },
          {
            name: "",
            rus: "Очистка сточных ям",
            eng: "Waste pit cleaning",
            uzb: "",
          },
          { name: "", rus: "Логистика", eng: "Logistics", uzb: "" },
          { name: "", rus: "Другое", eng: "Other", uzb: "" },
        ],
      },
      {
        name: "bus",
        path: "bus",
        rus: "Автобусы",
        eng: "Buses",
        uzb: "Avtobuslar",
      },
      {
        name: "trailers",
        path: "trailers",
        rus: "Прицепы",
        eng: "Trailers",
        uzb: "Treylerlar",
      },
      {
        name: "specialEquipment",
        path: "special-equipment",
        rus: "Спецтехника",
        eng: "Special machines",
        uzb: "Maxsus mashinalar",
      },
      {
        name: "agricultural",
        path: "agricultural-machinery",
        rus: "Сельхозтехника",
        eng: "Agricultural machines",
        uzb: "Qishloq xo'jaligi texnikasi",
      },
      {
        name: "sparesSpecialMachines",
        path: "spares-special-machines",
        rus: "Запчасти для техники",
        eng: "Spare parts for special/agricultural machines",
        uzb: "Maxsus/qishloq x. mashinalar ehtiyot qismlar",
      },
      {
        name: "waterTransport",
        path: "water-transport",
        rus: "Водный транспорт",
        eng: "Water transport",
        uzb: "Suv transporti",
      },
      {
        name: "other",
        path: "other-transport",
        rus: "Другое",
        eng: "Other",
        uzb: "Boshqalar",
      },
    ],
  },
  {
    name: "realEstate",
    path: "real-estate",
    rus: "Недвижимость",
    eng: "Real estate",
    uzb: "Ko'chmas mulk",
    pic: estate,
    activePic: activeEstate,
    id: 3,
    types: [
      {
        name: "dailyRent",
        path: "daily-rent",
        eng: "Daily rent",
        rus: "Посуточная аренда",
        uzb: "Kunlik ijara",
        types: [
          { name: "", rus: "Хостелы", eng: "", uzb: "" },
          { name: "", rus: "Гостиницы / Отели", eng: "", uzb: "" },
          { name: "", rus: "Квартиры", eng: "", uzb: "" },
          { name: "", rus: "Дома / Дачи", eng: "", uzb: "" },
          { name: "", rus: "Санатории / Дома отдыха", eng: "", uzb: "" },
        ],
      },
      {
        name: "apartments",
        path: "apartments",
        eng: "Apartments",
        uzb: "Kvartiralar",
        rus: "Квартиры",
      },
      {
        name: "houses",
        path: "houses",
        rus: "Дома, дачи",
        eng: "Houses, cottages",
        uzb: "Uylar, kottejlar",
      },
      {
        name: "offices",
        path: "offices",
        rus: "Коммерческие помещения",
        eng: "Offices",
        uzb: "Ofislar",
      },
      {
        name: "landAndPlots",
        path: "land-and-plots",
        rus: "Земля и участки",
        eng: "Land and plots",
        uzb: "Yer va uchastkalar",
      },
      {
        name: "garagesParking",
        path: "garages-parking",
        rus: "Гаражи / стоянки",
        eng: "Garages / Parking",
        uzb: "Garajlar / To'xtash joyi",
      },
      {
        name: "realtorServices",
        path: "realtor-services",
        rus: "Услуги риелтора",
        eng: "Realtor services",
        uzb: "Rieltorlik xizmatlari",
      },
      {
        name: "others",
        path: "other-real-estate",
        rus: "другое",
        uzb: "Boshqalar",
        eng: "Others",
      },
    ],
  },
  {
    name: "electronics",
    rus: "Электроника",
    eng: "Electronics",
    uzb: "Elektronika",
    pic: electronics,
    activePic: activeElectronics,
    path: "electronics",
    id: 4,
    types: [
      {
        name: "phones",
        path: "phones-communication",
        rus: "Телефоны и аксессуары",
        eng: "Phones and communications",
        uzb: "Telefonlar va aloqa",
        types: [
          { name: "", rus: "Аксессуары", eng: "", uzb: "" },
          { name: "", rus: "Мобильные телефоны / смартфоны", eng: "", uzb: "" },
          { name: "", rus: "Сим-карты / тарифы / номера", eng: "", uzb: "" },
          { name: "", rus: "Стационарные телефоны", eng: "", uzb: "" },
          { name: "", rus: "Прочие телефоны", eng: "", uzb: "" },
        ],
      },
      {
        name: "computersOfficeEquipment",
        path: "computers-office-equipment",
        rus: "Компьютеры, оргтехника",
        eng: "Computers, office equipment",
        uzb: "Kompyuterlar, ofis jihozlari",
        types: [
          { name: "", rus: "Настольные", eng: "", uzb: "" },
          { name: "", rus: "Ноутбуки", eng: "", uzb: "" },
          { name: "", rus: "Планшетные компьютеры", eng: "", uzb: "" },
          { name: "", rus: "Серверы", eng: "", uzb: "" },
          { name: "", rus: "Аксессуары", eng: "", uzb: "" },
          { name: "", rus: "Комплектующие", eng: "", uzb: "" },
          { name: "", rus: "Периферийные устройства", eng: "", uzb: "" },
          { name: "", rus: "Мониторы", eng: "", uzb: "" },
          { name: "", rus: "Внешние накопители", eng: "", uzb: "" },
          { name: "", rus: "Расходные материалы", eng: "", uzb: "" },
          { name: "", rus: "Другое", eng: "", uzb: "" },
        ],
      },
      {
        name: "appliances",
        path: "appliances",
        rus: "Бытовая техника",
        eng: "Appliances",
        uzb: "Maishiy texnika",
        forHome: {
          name: "forHome",
          rus: "Техника для дома",
          eng: "",
          uzb: "",
          types: [
            { name: "", rus: "Пылесосы", eng: "", uzb: "" },
            { name: "", rus: "Утюги", eng: "", uzb: "" },
            { name: "", rus: "Стиральные машины", eng: "", uzb: "" },
            { name: "", rus: "Швейные машины и оверлоки", eng: "", uzb: "" },
            { name: "", rus: "Вязальные машины", eng: "", uzb: "" },
            { name: "", rus: "Фильтры для воды", eng: "", uzb: "" },
            { name: "", rus: "Прочая техника для дома", eng: "", uzb: "" },
          ],
        },
        forKitchen: {
          name: "forKitchen",
          rus: "Техника для кухни",
          eng: "",
          uzb: "",
          types: [
            { name: "", rus: "Микроволновые печи", eng: "", uzb: "" },
            { name: "", rus: "Холодильники", eng: "", uzb: "" },
            { name: "", rus: "Плиты / печи", eng: "", uzb: "" },
            { name: "", rus: "Электрочайники", eng: "", uzb: "" },
            { name: "", rus: "Кофеварки / кофемолки", eng: "", uzb: "" },
            {
              name: "",
              rus: "Кухонные комбайны и измельчители",
              eng: "",
              uzb: "",
            },
            { name: "", rus: "Пароварки, мультиварки", eng: "", uzb: "" },
            { name: "", rus: "Хлебопечки", eng: "", uzb: "" },
            { name: "", rus: "Посудомоечные машины", eng: "", uzb: "" },
            { name: "", rus: "Вытяжки", eng: "", uzb: "" },
            { name: "", rus: "Прочая техника для кухни", eng: "", uzb: "" },
          ],
        },
      },
      {
        name: "tvs",
        path: "tvs",
        rus: "Тв / видеотехника",
        eng: "TVs",
        uzb: "Televizorlar",
        types: [
          { name: "", rus: "Медиа проигрыватели", eng: "", uzb: "" },
          { name: "", rus: "Телевизоры", eng: "", uzb: "" },
          { name: "", rus: "Аксессуары для ТВ/Видеотехники", eng: "", uzb: "" },
          { name: "", rus: "Спутниковое тв", eng: "", uzb: "" },
          { name: "", rus: "Прочая тв / видеотехника", eng: "", uzb: "" },
        ],
      },
      {
        name: "audioVideoDVDSSAT",
        path: "audio-video",
        rus: "Аудио",
        eng: "Audio",
        uzb: "Audio",
        types: [
          { name: "", rus: "Наушники", eng: "", uzb: "" },
          { name: "", rus: "Mp3 плееры", eng: "", uzb: "" },
          { name: "", rus: "Магнитолы", eng: "", uzb: "" },
          { name: "", rus: "Музыкальные центры", eng: "", uzb: "" },
          { name: "", rus: "Акустические системы", eng: "", uzb: "" },
          { name: "", rus: "Радиоприемники", eng: "", uzb: "" },
          { name: "", rus: "Портативная акустика", eng: "", uzb: "" },
          { name: "", rus: "Усилители / ресиверы", eng: "", uzb: "" },
          {
            name: "",
            rus: "Cd / md / виниловые проигрыватели",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "Прочая аудиотехника", eng: "", uzb: "" },
        ],
      },
      {
        name: "games",
        path: "games",
        rus: "Игры и игровые приставки",
        eng: "Games and game consoles",
        uzb: "O'yinlar va pristavkalari",
        types: [
          { name: "", rus: "Игры для приставок", eng: "", uzb: "" },
          { name: "", rus: "Приставки", eng: "", uzb: "" },
          { name: "", rus: "Игры для PC", eng: "", uzb: "" },
          { name: "", rus: "Аксессуары", eng: "", uzb: "" },
        ],
      },
      {
        name: "photoVideo",
        path: "photoAndVideo",
        rus: "Фото и Видео",
        eng: "Photo and Video",
        uzb: "Foto va Video",
        types: [
          { name: "", rus: "Пленочные фотоаппараты", eng: "", uzb: "" },
          { name: "", rus: "Цифровые фотоаппараты", eng: "", uzb: "" },
          { name: "", rus: "Видеокамеры", eng: "", uzb: "" },
          { name: "", rus: "Объективы", eng: "", uzb: "" },
          { name: "", rus: "Штативы / моноподы", eng: "", uzb: "" },
          { name: "", rus: "Фотовспышки", eng: "", uzb: "" },
          {
            name: "",
            rus: "Аксессуары для фото / видеокамер",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "Телескопы / бинокли", eng: "", uzb: "" },
        ],
      },
      {
        name: "batteriesAccumulators",
        path: "batteries",
        rus: "Батарейки, аккумуляторы",
        eng: "Batteries, accumulators",
        uzb: "Batareyalar, akkumulyatorlar",
      },
      {
        name: "individualCare",
        path: "individual-care",
        rus: "Индивидуальный уход",
        eng: "Personal care",
        uzb: "Shaxsiy g'amxo'rlik",
        types: [
          {
            name: "",
            rus: "Бритвы, эпиляторы, машинки для стрижки",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "Фены, укладка волос", eng: "", uzb: "" },
          { name: "", rus: "Весы", eng: "", uzb: "" },
          {
            name: "",
            rus: "Прочая техника для индивидуального ухода",
            eng: "",
            uzb: "",
          },
        ],
      },
      {
        name: "others",
        path: "other-electronics",
        rus: "Прочая электроника",
        eng: "Other electronics",
        uzb: "Boshqa elektronikalar",
      },
    ],
  },
  {
    name: "dressesShoes",
    path: "dresses-shoes",
    rus: "Мода / Стиль",
    eng: "Clothes, shoes",
    uzb: "Kiyim, poyabzal",
    pic: dresses,
    activePic: activeDresses,
    id: 5,
    types: [
      {
        name: "womensClothing",
        path: "womens-clothing",
        rus: "Женская одежда",
        eng: "Women's clothing",
        uzb: "Ayollar kiyimi",
        types: [
          {
            name: "forWedding",
            rus: "Для свадьбы",
            eng: "For wedding",
            uzb: "To'y uchun",
          },
          {
            name: "lingerie",
            rus: "Женское белье, купальники",
            eng: "Lingerie, swimwear",
            uzb: "Ichki kiyim, suzish kiyimlari",
          },
          {
            name: "forPregnant",
            rus: "Одежда для беременных",
            eng: "Clothes for pregnant women",
            uzb: "",
          },
        ],
      },
      {
        name: "mensClothing",
        path: "mens-clothing",
        rus: "Мужская одежда",
        eng: "Men's clothing",
        uzb: "Erkaklar kiyimi",
        types: [{ name: "", rus: "Мужское белье и плавки", eng: "", uzb: "" }],
      },
      {
        name: "childrensClothing",
        path: "childrens-clothing",
        rus: "Детская одежда, обувь",
        eng: "Children's clothing, footwear",
        uzb: "Bolalar kiyimlari, poyafzallari",
        types: [
          {
            name: "",
            rus: "Одежда для мальчиков",
            eng: "",
            uzb: "",
          },
          {
            name: "",
            rus: "Одежда для девочек",
            eng: "",
            uzb: "",
          },
          {
            name: "",
            rus: "Одежда для новорожденных",
            eng: "",
            uzb: "",
          },
          {
            name: "",
            rus: "Детская обувь",
            eng: "",
            uzb: "",
          },
        ],
      },
      {
        name: "shoes",
        path: "shoes",
        rus: "Обувь",
        eng: "Shoes",
        uzb: "Oyoq kiyimlari",
        types: [
          {
            name: "",
            rus: "Женская одежда",
            eng: "",
            uzb: "",
          },
          {
            name: "",
            rus: "Мужская обувь",
            eng: "",
            uzb: "",
          },
        ],
      },
      {
        name: "beautyHealth",
        path: "beauty-health",
        rus: "Красота / здоровье",
        eng: "Beauty / Health",
        uzb: "Go'zallik / Sog'lik",
        types: [
          { name: "", rus: "Косметика", eng: "", uzb: "" },
          { name: "", rus: "Парфюмерия", eng: "", uzb: "" },
          { name: "", rus: "Средства по уходу", eng: "", uzb: "" },
          { name: "", rus: "Прочие товары", eng: "", uzb: "" },
        ],
      },
      {
        name: "watchesGlassesBelts",
        path: "watches-glasses-belts",
        rus: "Часы, очки, ремни",
        eng: "Watches, glasses, belts",
        uzb: "Soatlar, ko'zoynaklar, kamarlar",
        types: [
          {
            name: "watches",
            rus: "Часы",
            eng: "Watches",
            uzb: "Soatlar",
            types: [
              {
                name: "",
                rus: "Женские часы",
                eng: "",
                uzb: "",
              },
              {
                name: "",
                rus: "Мужские часы",
                eng: "",
                uzb: "",
              },
              {
                name: "",
                rus: "Спортивные часы",
                eng: "",
                uzb: "",
              },
              {
                name: "",
                rus: "Унисекс часы",
                eng: "",
                uzb: "",
              },
            ],
          },
          {
            name: "glasses",
            rus: "Очки",
            eng: "Glasses",
            uzb: "Ko'zoynaklar",
          },
          {
            name: "belts",
            rus: "Ремни",
            eng: "Belts",
            uzb: "Kamarlar",
          },
        ],
      },
      {
        name: "bags",
        eng: "Bags",
        uzb: "Sumkalar",
        rus: "Сумки",
        path: "bags",
      },
      {
        name: "jewelry",
        path: "jewelry",
        rus: "Украшения Бижутерия",
        eng: "Jewelry Bijouterie",
        uzb: "Zargarlik bijuteriyasi",
      },
      {
        name: "overalls",
        path: "overalls",
        rus: "Спецодежда",
        eng: "Overalls",
        uzb: "Kombinezonlar",
      },
      {
        name: "others",
        path: "other-dresses",
        rus: "Разное",
        eng: "Others",
        uzb: "Boshqalar",
      },
    ],
  },
  {
    name: "building",
    path: "building",
    rus: "Строительство",
    eng: "Building",
    uzb: "Qurilish",
    pic: building,
    activePic: activeBuilding,
    id: 6,
    types: [
      {
        name: "buildingMaterials",
        path: "building-materials",
        rus: "Стройматериалы",
        eng: "Building materials",
        uzb: "Qurilish materiallari",
        type: [
          {
            name: "",
            rus: "Двери, окна, лестницы, заборы, замки",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "Кирпич, камень, брусчатка", eng: "", uzb: "" },
          { name: "", rus: "Материалы из дерева", eng: "", uzb: "" },
          { name: "", rus: "Отделочные материалы", eng: "", uzb: "" },
          {
            name: "",
            rus: "Песок, грант, щебень, чернозём, доломит",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "LED профили и ленты", eng: "", uzb: "" },
          { name: "", rus: "Арматура, металлоконструкции", eng: "", uzb: "" },
          { name: "", rus: "Бетон, готовый раствор", eng: "", uzb: "" },
          {
            name: "",
            rus: "Блоки питания, драйверы, контроллеры",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "Вентиляция", eng: "", uzb: "" },
          { name: "", rus: "Водосточная система", eng: "", uzb: "" },
          { name: "", rus: "Газобетон, керамзит", eng: "", uzb: "" },
          { name: "", rus: "Гидроизоляционные материалы", eng: "", uzb: "" },
          {
            name: "",
            rus: "Кольца канализации, трубы, стоки",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "Лампочки", eng: "", uzb: "" },
          { name: "", rus: "Масла, химия, отработка", eng: "", uzb: "" },
          { name: "", rus: "Материалы из металла", eng: "", uzb: "" },
          { name: "", rus: "Металлолом", eng: "", uzb: "" },
          { name: "", rus: "Мягкая кровля", eng: "", uzb: "" },
          { name: "", rus: "Перекрытия, балки", eng: "", uzb: "" },
          { name: "", rus: "Профиль для гипсокартона", eng: "", uzb: "" },
          { name: "", rus: "Регипс", eng: "", uzb: "" },
          { name: "", rus: "Столбы, вышки", eng: "", uzb: "" },
          { name: "", rus: "Утеплители", eng: "", uzb: "" },
          { name: "", rus: "Фасадные материалы", eng: "", uzb: "" },
          { name: "", rus: "Фундаментные блоки", eng: "", uzb: "" },
          { name: "", rus: "Химическое сырье", eng: "", uzb: "" },
          { name: "", rus: "Цемент, известь", eng: "", uzb: "" },
          { name: "", rus: "Шифер, черепица", eng: "", uzb: "" },
          { name: "", rus: "Электричество", eng: "", uzb: "" },
          { name: "", rus: "Другое", eng: "", uzb: "" },
        ],
      },
      {
        name: "toolAndTechnique",
        path: "tool-and-technique",
        rus: "Инструмент и техника",
        eng: "Tool and technique",
        uzb: "Asbob va texnika",
        types: [
          {
            name: "",
            rus: "Инструмент, станки, машины, оборудование",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "Строительная техника", eng: "", uzb: "" },
          { name: "", rus: "Другое", eng: "", uzb: "" },
        ],
      },
      {
        name: "toolRental",
        path: "tool-rental",
        rus: "Аренда инструмента",
        eng: "Tool rental",
        uzb: "Asbob ijarasi",
        type: [
          { name: "", rus: "Аренда инструмента", eng: "", uzb: "" },
          { name: "", rus: "Аренда спецтехники", eng: "", uzb: "" },
          { name: "", rus: "Разное", eng: "", uzb: "" },
        ],
      },
      {
        name: "plumbing",
        path: "plumbing",
        rus: "Сантехника",
        eng: "Plumbing",
        uzb: "Santexnika",
        types: [
          { name: "", rus: "Сантехника", eng: "", uzb: "" },
          { name: "", rus: "Отопительные системы и котлы", eng: "", uzb: "" },
        ],
      },
      {
        name: "gardenEquipment",
        path: "garden-equipment",
        rus: "Садовая техника",
        eng: "Garden equipment",
        uzb: "Bog' uskunalari",
        types: [
          { name: "", rus: "Аэраторы", eng: "", uzb: "" },
          { name: "", rus: "Бензопилы", eng: "", uzb: "" },
          { name: "", rus: "Минитракторы", eng: "", uzb: "" },
          { name: "", rus: "Мотоблоки", eng: "", uzb: "" },
          { name: "", rus: "Электропилы", eng: "", uzb: "" },
          { name: "", rus: "Газонокосилки", eng: "", uzb: "" },
          { name: "", rus: "Измельчители сучьев", eng: "", uzb: "" },
          { name: "", rus: "Лопаты, грабли", eng: "", uzb: "" },
          { name: "", rus: "Почвенные фрезы", eng: "", uzb: "" },
          { name: "", rus: "Сборщики листьев", eng: "", uzb: "" },
          {
            name: "",
            rus: "Снегоуборочные машины и агрегаты",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "Тачки, носилки", eng: "", uzb: "" },
          { name: "", rus: "Триммеры", eng: "", uzb: "" },
          { name: "", rus: "Шпалерные ножницы", eng: "", uzb: "" },
          { name: "", rus: "Плёнка", eng: "", uzb: "" },
          { name: "", rus: "Теплицы", eng: "", uzb: "" },
          { name: "", rus: "Садовая мебель и аксессуары", eng: "", uzb: "" },
          { name: "", rus: "Сельско-хозяйственная техника", eng: "", uzb: "" },
          { name: "", rus: "Разное", eng: "", uzb: "" },
        ],
      },
      {
        name: "projectsDesign",
        path: "projects-design",
        rus: "Проекты, дизайн",
        eng: "Projects, design",
        uzb: "Loyihalar, dizayn",
        types: [
          { name: "", rus: "Архитектурные проекты, планы", eng: "", uzb: "" },
          {
            name: "",
            rus: "Аэрофотосьемка местности и обьектов",
            eng: "",
            uzb: "",
          },
          {
            name: "",
            rus: "Геологические исследования, землемеры",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "Дизайн интерьеров и участков", eng: "", uzb: "" },
          { name: "", rus: "Разное", eng: "", uzb: "" },
        ],
      },
      {
        name: "transportationAndLoading",
        path: "transportation-and-loading",
        rus: "Перевозка и погрузка",
        eng: "Transportation and loading",
        uzb: "Tashish va yuklash",
        types: [
          { name: "", rus: "Пассажирские перевозки", eng: "", uzb: "" },
          { name: "", rus: "Бытовая техника, вещи", eng: "", uzb: "" },
          {
            name: "",
            rus: "Доставка хрупких и деликатных грузов",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "Железнодорожные перевозки", eng: "", uzb: "" },
          { name: "", rus: "Жидкие грузы", eng: "", uzb: "" },
          {
            name: "",
            rus: "Крупногабаритные грузоперевозки",
            eng: "",
            uzb: "",
          },
          { name: "", rus: "Курьерская доставка", eng: "", uzb: "" },
          { name: "", rus: "Международные перевозки TIR", eng: "", uzb: "" },
          { name: "", rus: "Морские перевозки", eng: "", uzb: "" },
          { name: "", rus: "Опасные и горючие грузы", eng: "", uzb: "" },
          { name: "", rus: "Перевозка и погрузка леса", eng: "", uzb: "" },
          { name: "", rus: "Перевозка мебели", eng: "", uzb: "" },
          { name: "", rus: "Стройматериалы и конструкции", eng: "", uzb: "" },
          { name: "", rus: "Сыпучие грузы", eng: "", uzb: "" },
          { name: "", rus: "Транспортировка животных", eng: "", uzb: "" },
          { name: "", rus: "Авиа перевозки", eng: "", uzb: "" },
          { name: "", rus: "Автоэвакуация", eng: "", uzb: "" },
          { name: "", rus: "Вывоз бытового мусора", eng: "", uzb: "" },
          { name: "", rus: "Вывоз мусора ( в контейнерах )", eng: "", uzb: "" },
          { name: "", rus: "Вывоз снега и листьев", eng: "", uzb: "" },
          { name: "", rus: "Очистка сточных ям", eng: "", uzb: "" },
          { name: "", rus: "Логистика", eng: "", uzb: "" },
          { name: "", rus: "Другое", eng: "", uzb: "" },
        ],
      },
    ],
  },
  {
    name: "home",
    path: "for-home",
    rus: "Для дома",
    eng: "For home",
    uzb: "Uy uchun",
    pic: home,
    activePic: activeHome,
    id: 7,
    types: [
      {
        name: "furnitureInterior",
        path: "furniture-interior",
        rus: "Мебель, интерьер",
        eng: "Furniture, interior",
        uzb: "Mebel, interyer",
        types: [
          { name: "", rus: "Для квартиры", eng: "", uzb: "" },
          { name: "", rus: "Для офиса", eng: "", uzb: "" },
          { name: "", rus: "Мебель на заказ", eng: "", uzb: "" },
          { name: "", rus: "Садовая мебель", eng: "", uzb: "" },
          { name: "", rus: "Специализированная мебель", eng: "", uzb: "" },
        ],
      },
      {
        name: "hand-madeProducts",
        path: "hand-made-products",
        rus: "Изделия ручной работы",
        eng: "Hand-made products",
        uzb: "Qo'lda tayyorlangan mahsulotlar",
      },
      {
        name: "antiquesPaintings",
        path: "antiques-paintings",
        rus: "Антиквариат, картины",
        eng: "Antiques, paintings",
        uzb: "Antikvar buyumlar, rasmlar",
      },
      {
        name: "housePlants",
        path: "house-plants",
        rus: "Домашние растения",
        eng: "House plants",
        uzb: "Uy o'simliklari",
      },
      {
        name: "other",
        eng: "Others",
        uzb: "Boshqalar",
        rus: "Другое",
        path: "other-home",
      },
    ],
  },
  {
    name: "gifts",
    rus: "Подарки",
    eng: "Gifts",
    uzb: "Sovg'alar",
    pic: gifts,
    activePic: activeGifts,
    path: "gifts",
    id: 13,
    types: [
      {
        name: "forWomen",
        path: "for-women",
        rus: "Для женщины",
        eng: "For women",
        uzb: "Qizlar uchun",
      },
      {
        name: "forMen",
        path: "for-men",
        rus: "Для мужчины",
        eng: "For men",
        uzb: "Erkaklar uchun",
      },
      {
        name: "paired",
        path: "paired",
        rus: "Парное",
        eng: "Paired",
        uzb: "Juftlik uchun",
      },
      {
        name: "forChildren",
        path: "for-children",
        rus: "Для ребёнка",
        eng: "For children",
        uzb: "Bolalar uchun",
      },
      {
        name: "certificates",
        path: "certificates",
        rus: "Сертификаты",
        eng: "Certificates",
        uzb: "Sertifikatlar",
      },
    ],
  },
  {
    name: "forChildren",
    path: "for-children",
    rus: "Для детей",
    eng: "For children",
    uzb: "Bolalar uchun",
    pic: children,
    activePic: activeChildren,
    id: 9,
    types: [
      {
        name: "strollers",
        path: "strollers",
        rus: "Коляски",
        eng: "Strollers",
        uzb: "Aravachalar",
      },
      {
        name: "carSeatsCarriers",
        path: "car-seats-carriers",
        rus: "Автокресла, переноски",
        eng: "Car seats, carriers",
        uzb: "Avtomobil o'rindiqlari, tashuvchilar",
      },
      {
        name: "childrensFurniture",
        path: "childrens-furniture",
        rus: "Детская мебель",
        eng: "Children's furniture",
        uzb: "Bolalar mebeli",
      },
      {
        name: "toysSwing",
        path: "toys-swing",
        rus: "Игрушки, качели",
        eng: "Toys, swing",
        uzb: "O'yinchoqlar, belanchak",
      },
      {
        name: "accessoriesAndNutrition",
        path: "accessories-and-nutrition",
        eng: "Accessories and nutrition",
        rus: "Аксессуары и питание",
        uzb: "Aksessuarlar va ovqatlanish",
      },
      {
        name: "circlesKindergartensSections",
        path: "circles-kindergartens-sections",
        rus: "Кружки, садики, секции",
        eng: "Circles, kindergartens, sections",
        uzb: "To'garaklar, bolalar bog'chalari, bo'limlar",
      },
      {
        name: "childrensActivities",
        path: "childrens-activities",
        rus: "Детские мероприятия",
        eng: "Children's activities",
        uzb: "Bolalar faoliyati",
      },
      {
        name: "everythingForSchool",
        path: "everything-for-school",
        rus: "Все для школы",
        eng: "Everything for school",
        uzb: "Maktab uchun hamma narsa",
      },
      {
        name: "others",
        path: "other-children",
        rus: "Разное",
        eng: "Others",
        uzb: "Boshqalar",
      },
    ],
  },
  {
    name: "animals",
    path: "animals",
    rus: "Животные",
    eng: "Animals",
    uzb: "Hayvonlar",
    pic: animals,
    activePic: activeAnimals,
    id: 10,
    types: [
      {
        name: "zooProducts",
        path: "zoo-products",
        rus: "Зоотовары",
        eng: "Zoo products",
        uzb: "Hayvonot bog'i mahsulotlari",
      },
      {
        name: "dogsPuppies",
        path: "dogs-puppies",
        rus: "Собаки, щенки",
        eng: "Dogs, puppies",
        uzb: "Itlar, kuchuklar",
      },
      {
        name: "catsKittens",
        path: "cats-kittens",
        rus: "Кошки, котята",
        eng: "Cats, kittens",
        uzb: "Mushuklar, mushukchalar",
      },
      {
        name: "rodents",
        path: "rodents",
        rus: "Грызуны",
        eng: "Rodents",
        uzb: "Kemiruvchilar",
      },
      {
        name: "parrotsAndBirds",
        path: "parrots-and-birds",
        rus: "Попугаи и птицы",
        eng: "Parrots and birds",
        uzb: "To'tiqushlar va qushlar",
      },
      {
        name: "fishAquariums",
        path: "fish-aquariums",
        rus: "Рыбки, аквариумы",
        eng: "Fish, aquariums",
        uzb: "Baliqlar, akvariumlar",
      },
      {
        name: "Exotic animals",
        path: "Exotic animals",
        rus: "Экзотические животные",
        eng: "Exotic animals",
        uzb: "Ekzotik hayvonlar",
      },
      {
        name: "farmAnimals",
        path: "farm-animals",
        rus: "Сельхоз животные",
        eng: "Farm animals",
        uzb: "Ferma hayvonlari",
      },
      {
        name: "veterinary",
        path: "veterinary",
        rus: "Ветеринария",
        eng: "Veterinary",
        uzb: "Veterinariya",
      },
      {
        name: "searchesFinds",
        path: "searches-finds",
        rus: "Поиски, находки",
        eng: "Searches, finds",
        uzb: "Qidiruv, topilmalar",
      },
      {
        name: "other",
        path: "other-animals",
        rus: "Разное",
        eng: "Others",
        uzb: "Boshqalar",
      },
    ],
  },
  {
    name: "agriculture",
    path: "agriculture",
    rus: "Сельское хозяйство",
    eng: "Agriculture",
    uzb: "Qishloq xo'jaligi",
    pic: agriculture,
    activePic: activeAgriculture,
    id: 11,
    types: [
      {
        name: "agricuturalWork",
        path: "Agricultural-work",
        rus: "Сельхозработы",
        eng: "Agricultural work",
        uzb: "Qishloq xo'jaligi ishi",
      },
      {
        name: "",
        path: "",
        rus: "Овощеводство / садоводство",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Удобрения и химикаты",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Семена и рассада",
        eng: "",
        uzb: "",
      },
      {
        name: "others",
        path: "other-agriculture",
        rus: "Разное",
        eng: "Others",
        uzb: "Boshqalar",
      },
    ],
  },
  {
    name: "leisureHobbies",
    path: "entertainment-holiday",
    rus: "Отдых увлечения",
    eng: "Leisure hobbies",
    uzb: "Sevimli mashg'ulotlar",
    pic: holiday,
    activePic: activeHoliday,
    id: 12,
    types: [
      {
        name: "hobbies",
        path: "hobby",
        rus: "Хобби, увлечения",
        eng: "Hobbies",
        uzb: "Sevimli mashg'ulotlar",
      },
      {
        name: "collecting",
        path: "collecting",
        rus: "Коллекционирование",
        eng: "Collecting",
        uzb: "Yig'ish",
      },
      {
        name: "ticketsConcertsWhereToGo",
        path: "tickets-concerts-where-to-go",
        rus: "Билеты, концерты, куда пойти",
        eng: "Tickets, concerts, where to go",
        uzb: "Chiptalar, konsertlar, qaerga borish",
      },
      {
        name: "musicInstrumentsLearning",
        path: "music-instruments-learning",
        rus: "Музыка, инструменты, обучение",
        eng: "Music, instruments, learning",
        uzb: "Musiqa, asboblar, o'rganish",
      },
      {
        name: "books",
        path: "books",
        rus: "Книги",
        eng: "Books",
        uzb: "Kitoblar",
      },
      {
        name: "sportsActiveRecreation",
        path: "sports-active-recreation",
        rus: "Спорт, активный отдых",
        eng: "Sports, active recreation",
        uzb: "Sport, faol dam olish",
      },
      {
        name: "huntingFishing",
        path: "hunting-fishing",
        rus: "Охота, рыбалка",
        eng: "Hunting Fishing",
        uzb: "Ovchilik Baliq ovlash",
      },
      {
        name: "tourism",
        path: "tourism",
        rus: "Туризм",
        eng: "Tourism",
        uzb: "Turizm",
      },
      {
        name: "others",
        eng: "Others",
        uzb: "Boshqalar",
        rus: "Всё остальное",
        path: "other-entertainment",
      },
    ],
  },
  {
    name: "services",
    path: "services",
    rus: "Сервисы",
    eng: "Services",
    uzb: "Xizmatlar",
    pic: services,
    activePic: activeServices,
    id: 8,
    types: [
      {
        name: "",
        path: "",
        rus: "Строительство / ремонт / уборка",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Реклама / полиграфия / маркетинг / интернет",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Няни / сиделки",
        eng: "",
        uzb: "",
      },
      {
        path: "transportationAndLoading",
        name: "transportation-and-loading",
        rus: "Перевозка и погрузка",
        eng: "Transportation and loading",
        uzb: "Tashish va yuklash",
      },
      {
        name: "",
        path: "",
        rus: "Сырьё / материалы",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Красота / здоровье",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Образование",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Услуги для животных",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Развлечения / Искусство / Фото / Видео",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Авто / мото услуги",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Ремонт техники",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Прокат товаров",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Продажа бизнеса",
        eng: "",
        uzb: "",
      },
      {
        name: "",
        path: "",
        rus: "Прочие услуги",
        eng: "",
        uzb: "",
      },
    ],
  },
  {
    name: "providers",
    path: "providers",
    rus: "Поставщики",
    eng: "Providers",
    uzb: "Yetkazib beruvchilar",
    pic: providers,
    activePic: activeProviders,
    id: 14,
    types: [
      {
        name: "wholesale",
        path: "wholesale",
        rus: "Оптовые продажи",
        eng: "Wholesale",
        uzb: "Ulgurji savdo",
      },
      {
        name: "forConstruction",
        path: "for-construction",
        rus: "Для строительства",
        eng: "For construction",
        uzb: "Qurilish uchun",
      },
      {
        name: "forAnimals",
        path: "for-animals",
        eng: "For animals",
        uzb: "Hayvonlar uchun",
        rus: "Для животных",
      },
      {
        name: "forClothes",
        path: "for-clothes",
        rus: "Для одежды",
        eng: "For clothes",
        uzb: "Kiyim uchun",
      },
      {
        name: "electronics",
        path: "electronics",
        rus: "Электротехника",
        eng: "Electronics",
        uzb: "Elektronika",
      },
      {
        name: "furniture",
        path: "furniture",
        rus: "Мебель",
        eng: "Furniture",
        uzb: "Mebel",
      },
      {
        name: "plumbing",
        path: "plumbing",
        rus: "Сантехника",
        eng: "Plumbing",
        uzb: "Santexnika",
      },
      {
        name: "others",
        eng: "Others",
        uzb: "Boshqalar",
        rus: "Другое",
        path: "other-providers",
      },
    ],
  },
];
