export const animalHusbandry = [
  { name: "", value: "Farm animals" },
  { name: "", value: "Dressing" },
  { name: "", value: "Feed" },
  { name: "", value: "Rabbit breeding" },
  { name: "", value: "Fur farming" },
  { name: "", value: "Pasture equipment" },
  { name: "", value: "Equipment for barns" },
  { name: "", value: "Dairy equipment" },
  { name: "", value: "Pig Farm Equipment" },
  { name: "", value: "Apiary equipment" },
  { name: "", value: "Hunting, breeding of wild animals" },
  { name: "", value: "Veterinary services and medicines" },
  { name: "", value: "Dairy products" },
  { name: "", value: "Food" },
  { name: "", value: "Other" },
];

export const poultryFarming = [
  { name: "", value: "Geese" },
  { name: "", value: "Turkeys" },
  { name: "", value: "Chickens" },
  { name: "", value: "Ostriches" },
  { name: "", value: "Ducks" },
  { name: "", value: "Poultry meat" },
  { name: "", value: "Sale of eggs " },
  { name: "", value: "Feed" },
  { name: "", value: "Poultry farm equipment" },
  { name: "", value: "Veterinary services and medicines" },
  { name: "", value: "Other" },
];

export const fisheries = [
  { name: "", value: "Live fish, fry" },
  { name: "", value: "Fish food" },
  { name: "", value: "Fish farming equipment" },
  { name: "", value: "Tackle, fishing rods, fishing equipment" },
  { name: "", value: "Veterinary services and medicines" },
  { name: "", value: "Fish and fish products" },
  { name: "", value: "Other" },
];

export const agriculturalMachinery = [
  { name: "", value: "Tractors" },
  { name: "", value: "Combines and forage harvesters" },
  { name: "", value: "Tillage equipment" },
  { name: "", value: "Forage equipment" },
  { name: "", value: "Seeding equipment" },
  { name: "", value: "Fertilizer application equipment" },
  { name: "", value: "Grinders, crushers, mills" },
  { name: "", value: "Skid steer loaders" },
  { name: "", value: "Front loaders" },
  { name: "", value: "Trailers" },
  { name: "", value: "Attachments" },
  { name: "", value: "Bunkers, tanks, elevators" },
  { name: "", value: "Sorting machinery and equipment" },
  { name: "", value: "Electrical equipment" },
  { name: "", value: "Garden equipment" },
  { name: "", value: "Other agricultural equipment" },
  { name: "", value: "Spare parts" },
  { name: "", value: "Agricultural antiques" },
  { name: "", value: "Miscellaneous" },
];

export const vegetableGrowingGardening = [
  { name: "", value: "Film" },
  { name: "", value: "Glass" },
  { name: "", value: "Greenhouses" },
  { name: "", value: "Seedlings, seeds" },
  { name: "", value: "Garden plants" },
  { name: "", value: "Saplings, fruit trees" },
  { name: "", value: "Wheelbarrows, stretchers" },
  { name: "", value: "Garden equipment, shovels, rakes" },
  { name: "", value: "Fertilizers, earth" },
  { name: "", value: "Boxes, packaging, containers" },
  { name: "", value: "Vegetable gardens, gardens" },
  { name: "", value: "Garden furniture and accessories" },
  { name: "", value: "Tools, construction equipment" },
  { name: "", value: "Processing equipment" },
  { name: "", value: "Building material" },
  { name: "", value: "Transport Services" },
  { name: "", value: "Site designer services" },
  { name: "", value: "Surveyor services, geology" },
  { name: "", value: "Garden and lawn care" },
  { name: "", value: "Other" },
  { name: "", value: "Vegetables" },
  { name: "", value: "Fruits" },
  { name: "", value: "Food" },
];

export const food = [
  { name: "", value: "Mushrooms" },
  { name: "", value: "Grain and flour " },
  { name: "", value: "Sausages" },
  { name: "", value: "Confectionery" },
  { name: "", value: "Canned products " },
  { name: "", value: "Canned food " },
  { name: "", value: "Smoking" },
  { name: "", value: "Culinary products " },
  { name: "", value: "Honey" },
  { name: "", value: "Dairy products " },
  { name: "", value: "Poultry meat " },
  { name: "", value: "Vegetables" },
  { name: "", value: "Food equipment" },
  { name: "", value: "Semi-finished products" },
  { name: "", value: "Fish and fish products " },
  { name: "", value: "Fresh meat" },
  { name: "", value: "Juices" },
  { name: "", value: "Pickles" },
  { name: "", value: "Fruits" },
  { name: "", value: "Bakery products" },
  { name: "", value: "Berries" },
  { name: "", value: "Eggs" },
  { name: "", value: "Spices" },
  { name: "", value: "Other meat products" },
  { name: "", value: "Other food" },
  { name: "", value: "Household appliances" },
];

export const other = [
  { name: "", value: "Agricultural work" },
  { name: "", value: "Fertilizers and chemicals " },
  { name: "", value: "Seeds and seedlings " },
  { name: "", value: "Miscellaneous" },
];
