export const furnitureInterior = [
  { name: "Sofas, beds" },
  { name: "Armchairs, chairs" },
  { name: "Tables" },
  { name: "Chandeliers, sconces" },
  { name: "Kitchens, kitchen sets" },
  { name: "Bedside tables, chests of drawers" },
  { name: "Cabinets" },
  { name: "Shelves, stands, hangers" },
  { name: "Sections" },
  { name: "Mirrors" },
  { name: "Carpets" },
  { name: "Furniture sets" },
  { name: "Hallways" },
  { name: "Sleeping sets" },
  { name: "Dining sets" },
  { name: "Blinds, curtains" },
  { name: "Blankets, pillows, sheets" },
  { name: "Crockery, cutlery" },
  { name: "Garden furniture and accessories" },
  { name: "Children's furniture" },
  { name: "Office furniture and accessories" },
  { name: "Bathroom furniture and accessories" },
  { name: "Doors, windows, stairs" },
  { name: "Plumbing" },
  { name: "Fittings, accessories" },
  { name: "Safes" },
  { name: "Furniture manufacturing" },
  { name: "Furniture repair" },
  { name: "Transportation of furniture" },
  { name: "Furniture cleaning" },
  { name: "Designer services" },
  { name: "Household appliances" },
  { name: "Clock" },
  { name: "Bulbs" },
  { name: "Miscellaneous" },
];

export const healthBeauty = [
  { name: "Beauty, appearance" },
  { name: "Health" },
  { name: "Medical services" },
  { name: "Massage services" },
  { name: "Aerobics, fitness, yoga" },
  { name: "Courses for make-up artists, stylists" },
  { name: "Hairdressing courses" },
  { name: "Manicure courses" },
  { name: "Dancing" },
  { name: "Accessories" },
];

export const jewelsDecorations = [
  { name: "Jewelry" },
  { name: "Bracelets" },
  { name: "Brooches, medallions" },
  { name: "Gems" },
  { name: "Necklace" },
  { name: "Rings" },
  { name: "Pendants" },
  { name: "Earrings" },
  { name: "Chains" },
  { name: "Watches" },
  { name: "Accessories" },
  { name: "Pawnshop services" },
  { name: "Jewelers Services" },
  { name: "Miscellaneous" },
  { name: "Coins" },
];

export const giftsSouvenirsHandicrafts = [
  { name: "Pet accessories" },
  { name: "Beads" },
  { name: "Interior decor" },
  { name: "For celebrations" },
  { name: "Paintings and panels" },
  { name: "Cosmetics" },
  { name: "Dolls and toys" },
  { name: "Shoes" },
  { name: "Clothing" },
  { name: "Crockery" },
  { name: "Wedding accessories" },
  { name: "Souvenirs and gifts" },
  { name: "Bags, belts, accessories" },
  { name: "Flowers, floristry" },
  { name: "Sewing, knitting, embroidery" },
  { name: "Master classes" },
  { name: "Consumables" },
  { name: "Other" },
];

export const antiquesPaintings = [
  { name: "Antiques" },
  { name: "Antique furniture" },
  { name: "Paintings" },
  { name: "Miscellaneous" },
  { name: "Collecting" },
];

export const housePlants = [
  { name: "Scarlet" },
  { name: "Bonsai" },
  { name: "Diefenbachia" },
  { name: "Dracaena" },
  { name: "Cacti" },
  { name: "Palm trees" },
  { name: "Ferns" },
  { name: "Tradescantia" },
  { name: "Violets" },
  { name: "Ficuses" },
  { name: "Flowers" },
  { name: "Ekibans" },
  { name: "Small plants" },
  { name: "Medium plants" },
  { name: "Large plants" },
  { name: "Ornamental plants" },
  { name: "Artificial plants" },
  { name: "Medicinal plants" },
  { name: "Fruit trees, seedlings" },
  { name: "Garden plants" },
  { name: "Outdoor plants" },
  { name: "Land and fertilizers" },
  { name: "Other" },
];

export const homeOther = [
  { name: "Firewood, briquettes, pellets" },
  { name: "Detergents" },
  { name: "Food" },
  { name: "Garden equipment" },
  { name: "Household appliances" },
  { name: "Video surveillance systems" },
  { name: "Household work" },
  { name: "Miscellaneous" },
];
