export const hobbies = [
  { name: "", value: "Astronomy" },
  { name: "", value: "Painting, drawing" },
  { name: "", value: "Handicrafts" },
  { name: "", value: "Art" },
  { name: "", value: "Cinema" },
  { name: "", value: "Metal detectors and treasure hunting" },
  { name: "", value: "RC models" },
  { name: "", value: "Needlework, beads" },
  { name: "", value: "Smart home, Arduino, Raspberry PI" },
  { name: "", value: "Floristry" },
  { name: "", value: "Sewing, knitting, embroidery" },
  { name: "", value: "Miscellaneous" },
];

export const collectiong = [
  { name: "", value: "Coins, banknotes" },
  { name: "", value: "Military relics" },
  { name: "", value: "Badges, buttons" },
  { name: "", value: "Historical artifacts" },
  { name: "", value: "Stamps and envelopes" },
  { name: "", value: "Modeling, collection models" },
  { name: "", value: "Awards, orders" },
  { name: "", value: "Postcards, booklets" },
  { name: "", value: "Figurines" },
  { name: "", value: "Banks, corks" },
  { name: "", value: "Antiques" },
  { name: "", value: "Miscellaneous" },
];

export const ticketsConcerts = [
  { name: "", value: "Concert tickets" },
  { name: "", value: "Tickets, ballet, opera, symphonies" },
  { name: "", value: "Tickets, sports events" },
  { name: "", value: "Tickets, theater" },
  { name: "", value: "Tickets, show programs" },
  { name: "", value: "Announcements" },
  { name: "", value: "Bars, Cafes " },
  { name: "", value: "Exhibitions" },
  { name: "", value: "Hotels" },
  { name: "", value: "Children's activities" },
  { name: "", value: "Night clubs" },
  { name: "", value: "Organization of holidays, events" },
  { name: "", value: "Restaurants" },
  { name: "", value: "Sports activities" },
  { name: "", value: "Bus tickets" },
  { name: "", value: "Train tickets" },
  { name: "", value: "Ferry tickets" },
  { name: "", value: "Other" },
];

export const musicInstrumentsLearning = [
  { name: "", value: "Musical instruments" },
  { name: "", value: "Accessories" },
  { name: "", value: "Acoustics, electronics" },
  { name: "", value: "CD, cassettes" },
  { name: "", value: "Teaching music, vocals" },
  { name: "", value: "Recording studios" },
  { name: "", value: "Musician Services" },
  { name: "", value: "Photographic services" },
  { name: "", value: "Miscellaneous" },
];

export const books = [
  { name: "", value: "Geography" },
  { name: "", value: "Children's literature" },
  { name: "", value: "Foreign classics" },
  { name: "", value: "Foreign languages" },
  { name: "", value: "History" },
  { name: "", value: "Latvian literature" },
  { name: "", value: "Medical Literature" },
  { name: "", value: "Religious Literature" },
  { name: "", value: "Russian classic" },
  { name: "", value: "Modern foreign literature" },
  { name: "", value: "Contemporary Russian Literature" },
  { name: "", value: "References" },
  { name: "", value: "Textbooks" },
  { name: "", value: "Philosophy" },
  { name: "", value: "Fiction" },
  { name: "", value: "Non-fiction" },
  { name: "", value: "Periodicals" },
  { name: "", value: "Antique books" },
  { name: "", value: "Miscellaneous" },
];

export const sports = [
  { name: "", value: "Aviation" },
  { name: "", value: "Motorsport" },
  { name: "", value: "Airsoft, airsoft" },
  { name: "", value: "Mountaineering" },
  { name: "", value: "Basketball" },
  { name: "", value: "Running & Athletics" },
  { name: "", value: "Cross-country skiing" },
  { name: "", value: "Billiards" },
  { name: "", value: "Wakeboard, Water skiing" },
  { name: "", value: "Windsurfing" },
  { name: "", value: "Volleyball" },
  { name: "", value: "Golf" },
  { name: "", value: "Alpine skiing" },
  { name: "", value: "Diving" },
  { name: "", value: "Martial arts " },
  { name: "", value: "Yoga" },
  { name: "", value: "Kitesurfing" },
  { name: "", value: "Motorsport" },
  { name: "", value: "Board games" },
  { name: "", value: "Novus" },
  { name: "", value: "Paragliders, hang gliders" },
  { name: "", value: "Parachuting" },
  { name: "", value: "Paintball" },
  { name: "", value: "Swimming" },
  { name: "", value: "Scuba diving" },
  { name: "", value: "Rugby" },
  { name: "", value: "Rollers" },
  { name: "", value: "Squash" },
  { name: "", value: "Skateboarding" },
  { name: "", value: "Sports shooting" },
  { name: "", value: "Race walking" },
  { name: "", value: "Dancing" },
  { name: "", value: "Tennis" },
  { name: "", value: "Fitness equipment" },
  { name: "", value: "Figure skating" },
  { name: "", value: "Floorball" },
  { name: "", value: "Football" },
  { name: "", value: "Ice hockey" },
  { name: "", value: "Artistic gymnastics" },
  { name: "", value: "Chess, backgammon" },
  { name: "", value: "Yachts, boats, water recreation snowboard" },
  { name: "", value: "SUP surfing" },
  { name: "", value: "Travel equipment" },
  { name: "", value: "Equipment" },
  { name: "", value: "Miscellaneous" },
];

export const huntingFishing = [
  { name: "", value: "Footwear for hunting and fishing" },
  { name: "", value: "Clothes for hunting and fishing" },
  { name: "", value: "Weapons" },
  { name: "", value: "Spearfishing" },
  { name: "", value: "Travel equipment" },
  { name: "", value: "Fishing rods and tackle" },
  { name: "", value: "Fishing spots" },
  { name: "", value: "Knives" },
  { name: "", value: "Fishfinders" },
  { name: "", value: "Boats, water transport" },
  { name: "", value: "Other" },
];

export const tourism = [
  { name: "", value: "Baths" },
  { name: "", value: "Travel equipment" },
  { name: "", value: "Holiday houses" },
  { name: "", value: "Registration of visas and documents" },
  { name: "", value: "Foreign tours" },
  { name: "", value: "Rural tourism" },
  { name: "", value: "Hotels and hostels" },
  { name: "", value: "Campsites and tourist sites" },
  { name: "", value: "Tourist transport rental, charters" },
  { name: "", value: "Search for a travel companion" },
  { name: "", value: "Miscellaneous" },
];

export const other = [
  { name: "", value: "Dating" },
  { name: "", value: "Everything else" },
];
