export const transport = {
  passengerCars: { name: "Passenger cars" },
  trucks: { name: "Trucks" },
  motoTransport: { name: "Moto transport" },
  bicyclesScooters: { name: "Bicycles, scooters" },
  carExchange: { name: "Car exchange" },
  sparePartsAndAccessories: { name: "Spare parts and accessories" },
  repairAndSpareParts: { name: "Repair and spare parts" },
  transportationOfGoodsAndPeople: {
    name: "Transportation of goods and people",
  },
  transportRental: { name: "Transport rental" },
  buggy: { name: "Buggy" },
  atvAndAmphibians: { name: "ATVs & Amphibians" },
  waterTransport: { name: "Water transport" },
  karting: { name: "Karting" },
  hangGliders: { name: "Hang gliders" },
  paragliders: { name: "Paragliders" },
  aircraft: { name: "Aircraft" },
  otherVehicles: { name: "Other vehicles" },
  canistersTanks: { name: "Canisters, tanks" },
  oilsChemistryMining: { name: "Oils, chemistry, mining" },
  carExchange: { name: "Car exchange" },
  trailers: { name: "Trailers and trailers" },
  transportForTheDisabled: { name: "Transport for the disabled" },
  transportWithDefectsOrAfterAnAccident: {
    name: "Transport with defects or after an accident",
  },
  Miscellaneous: { name: "Miscellaneous" },
};
