export const works = [
  { name: "", value: "Aviation Specialist" },
  { name: "", value: "Car tinsmith" },
  { name: "", value: "Crane Operator" },
  { name: "", value: "Car painter" },
  { name: "", value: "Auto mechanic" },
  { name: "", value: "Car wash" },
  { name: "", value: "Car mechanic" },
  { name: "", value: "Auto electrician" },
  { name: "", value: "Agent" },
  { name: "", value: "Real estate agent" },
  { name: "", value: "Advertising agent" },
  { name: "", value: "Agronomist" },
  { name: "", value: "Administrator" },
  { name: "", value: "Actor" },
  { name: "", value: "Climber, high-altitude" },
  { name: "", value: "Analyst" },
  { name: "", value: "Operator" },
  { name: "", value: "Rebar" },
  { name: "", value: "Archivist" },
  { name: "", value: "Architect" },
  { name: "", value: "Assistant" },
  { name: "", value: "Bath attendant" },
  { name: "", value: "Bartender" },
  { name: "", value: "Concrete worker" },
  { name: "", value: "Brigadier" },
  { name: "", value: "Bulldozer" },
  { name: "", value: "Accountant" },
  { name: "", value: "Veterinarian" },
  { name: "", value: "Makeup artist" },
  { name: "", value: "Driver" },
  { name: "", value: "Vocalist" },
  { name: "", value: "Doctor" },
  { name: "", value: "Physician assistant" },
  { name: "", value: "knitter" },
  { name: "", value: "Maid" },
  { name: "", value: "Loader" },
  { name: "", value: "Janitor" },
  { name: "", value: "Duty officer" },
  { name: "", value: "Declarant" },
  { name: "", value: "Clerk" },
  { name: "", value: "Designer" },
  { name: "", value: "Director" },
  { name: "", value: "Dispatcher" },
  { name: "", value: "Docker" },
  { name: "", value: "Housekeeper" },
  { name: "", value: "Milkmaid" },
  { name: "", value: "Tinsmith" },
  { name: "", value: "Animal breeder" },
  { name: "", value: "Journalist" },
  { name: "", value: "Manager" },
  { name: "", value: "Engineer" },
  { name: "", value: "Instructor" },
  { name: "", value: "Bricklayer" },
  { name: "", value: "Captain" },
  { name: "", value: "Cashier" },
  { name: "", value: "Storekeeper" },
  { name: "", value: "Picker" },
  { name: "", value: "Computer technician" },
  { name: "", value: "Confectioner" },
  { name: "", value: "Constructor" },
  { name: "", value: "Consultant" },
  { name: "", value: "Controller" },
  { name: "", value: "Cosmetologist" },
  { name: "", value: "Crane Operator" },
  { name: "", value: "Roofer" },
  { name: "", value: "Croupier" },
  { name: "", value: "Courier" },
  { name: "", value: "Laboratory assistant" },
  { name: "", value: "Lumberjack" },
  { name: "", value: "Logist" },
  { name: "", value: "Layout designer" },
  { name: "", value: "Broker" },
  { name: "", value: "Painter" },
  { name: "", value: "Manicurist" },
  { name: "", value: "Masseur" },
  { name: "", value: "Car service master" },
  { name: "", value: "Train driver" },
  { name: "", value: "Furniture maker" },
  { name: "", value: "Nurse" },
  { name: "", value: "Manager" },
  { name: "", value: "HR manager" },
  { name: "", value: "Mechanic" },
  { name: "", value: "Model" },
  { name: "", value: "Washer" },
  { name: "", value: "Installer" },
  { name: "", value: "Sailor" },
  { name: "", value: "Paver" },
  { name: "", value: "Musician" },
  { name: "", value: "Butcher" },
  { name: "", value: "Typesetter" },
  { name: "", value: "Repairman" },
  { name: "", value: "Babysitter" },
  { name: "", value: "Window maker" },
  { name: "", value: "Operator" },
  { name: "", value: "Waiter" },
  { name: "", value: "Decorator" },
  { name: "", value: "Security guard" },
  { name: "", value: "Appraiser" },
  { name: "", value: "Hairdresser" },
  { name: "", value: "Teacher" },
  { name: "", value: "Baker" },
  { name: "", value: "Translator" },
  { name: "", value: "Pechnik" },
  { name: "", value: "Sawyer" },
  { name: "", value: "Tiler" },
  { name: "", value: "Carpenter" },
  { name: "", value: "Cook" },
  { name: "", value: "Assistant" },
  { name: "", value: "Tailor" },
  { name: "", value: "Porter, porter" },
  { name: "", value: "Dishwasher" },
  { name: "", value: "Postman" },
  { name: "", value: "Teacher" },
  { name: "", value: "Programmer" },
  { name: "", value: "Seller" },
  { name: "", value: "Foreman" },
  { name: "", value: "Psychologist" },
  { name: "", value: "Worker" },
  { name: "", value: "Printing house worker" },
  { name: "", value: "Radio engineer" },
  { name: "", value: "Handyman" },
  { name: "", value: "Advertising manager" },
  { name: "", value: "Fisherman" },
  { name: "", value: "Fish processor" },
  { name: "", value: "Gardener" },
  { name: "", value: "Plumber" },
  { name: "", value: "Shoemaker" },
  { name: "", value: "Collector" },
  { name: "", value: "Welder" },
  { name: "", value: "Secretary" },
  { name: "", value: "Network administrator" },
  { name: "", value: "Nurse" },
  { name: "", value: "Locksmith" },
  { name: "", value: "Estimator" },
  { name: "", value: "Supplier" },
  { name: "", value: "Sorter" },
  { name: "", value: "Social worker" },
  { name: "", value: "Specialist" },
  { name: "", value: "Glazier" },
  { name: "", value: "Carpenter" },
  { name: "", value: "Dentist" },
  { name: "", value: "Builder" },
  { name: "", value: "Steward" },
  { name: "", value: "Dancer" },
  { name: "", value: "Technician" },
  { name: "", value: "Technologist" },
  { name: "", value: "Merchandiser" },
  { name: "", value: "Turner" },
  { name: "", value: "Tractor driver" },
  { name: "", value: "Coach" },
  { name: "", value: "Tour operator" },
  { name: "", value: "Cleaning lady" },
  { name: "", value: "Packer" },
  { name: "", value: "Pharmacist" },
  { name: "", value: "Financial Analyst" },
  { name: "", value: "Florist" },
  { name: "", value: "Photographer" },
  { name: "", value: "Model" },
  { name: "", value: "Milling machine" },
  { name: "", value: "Artist" },
  { name: "", value: "Seamstress" },
  { name: "", value: "Silkscreen" },
  { name: "", value: "Chef" },
  { name: "", value: "Tire fitter" },
  { name: "", value: "Plasterer" },
  { name: "", value: "Economist" },
  { name: "", value: "Excavator" },
  { name: "", value: "Electrician" },
  { name: "", value: "Electric Welder" },
  { name: "", value: "Lawyer" },
  { name: "", value: "Linux administrator" },
  { name: "", value: "Web designer" },
  { name: "", value: "Web developer" },
  { name: "", value: "Other professions" },
];

export const coursesEducation = [
  { name: "", value: "Driving courses" },
  { name: "", value: "Acting courses" },
  { name: "", value: "Accounting courses" },
  { name: "", value: "Courses for make-up artists, stylists" },
  { name: "", value: "Interior design courses" },
  { name: "", value: "Landscape designer courses" },
  { name: "", value: "Computer courses" },
  { name: "", value: "Courses for nannies, housekeepers" },
  { name: "", value: "Security guard courses" },
  { name: "", value: "Hairdressing courses" },
  { name: "", value: "Pilot courses" },
  { name: "", value: "Manicure, pedicure courses" },
  { name: "", value: "Psychology courses" },
  { name: "", value: "Courses for cooks and confectioners" },
  { name: "", value: "Florist courses" },
  { name: "", value: "Sewing and needlework courses" },
  { name: "", value: "Musical training and singing" },
  { name: "", value: "Study Abroad" },
  { name: "", value: "Advanced training" },
  { name: "", value: "Professional courses" },
  { name: "", value: "Seminars and trainings" },
  { name: "", value: "Sports training" },
  { name: "", value: "Dancing" },
  { name: "", value: "Language courses" },
  { name: "", value: "Miscellaneous" },
  { name: "", value: "Coursework, essays, diplomas" },
  { name: "", value: "Tutoring" },
  { name: "", value: "For children" },
  { name: "", value: "Sports" },
];

export const businessContacts = [
  { name: "", value: "Business cards, souvenirs, stickers" },
  { name: "", value: "Company announcements" },
  { name: "", value: "Seals, stamps, seals" },
  { name: "", value: "Search for dealers, retailers" },
  { name: "", value: "Search for distributors" },
  { name: "", value: "Search for an investor" },
  { name: "", value: "Search for partners" },
  { name: "", value: "Polygraphy and printing" },
  { name: "", value: "Holding auctions" },
  { name: "", value: "Sale of business, companies" },
  { name: "", value: "Advertising" },
  { name: "", value: "Expertise and evaluation" },
  { name: "", value: "Miscellaneous" },
  { name: "", value: "Accounting services" },
  { name: "", value: "Debt recovery" },
  { name: "", value: "Company registration" },
  { name: "", value: "Construction" },
];

export const legalServices = [
  { name: "", value: "Administrative matters" },
  { name: "", value: "Accounting services" },
  { name: "", value: "Debt recovery" },
  { name: "", value: "Civil cases" },
  { name: "", value: "Notaries" },
  { name: "", value: "Registration of visas and documents" },
  { name: "", value: "Company registration" },
  { name: "", value: "Family law" },
  { name: "", value: "Transaction support" },
  { name: "", value: "Criminal cases" },
  { name: "", value: "Expertise and evaluation" },
  { name: "", value: "Legal services for companies" },
  { name: "", value: "Miscellaneous" },
];

export const financial = [
  { name: "", value: "Audit, asset valuation" },
  { name: "", value: "Accounting services" },
  { name: "", value: "Loans and leasing" },
  { name: "", value: "Tax and financial advice" },
  { name: "", value: "Miscellaneous" },
];

export const translation = [
  { name: "", value: "English" },
  { name: "", value: "Russian" },
  { name: "", value: "Uzbek" },
  { name: "", value: "German" },
  { name: "", value: "Other" },
];

export const internet = [
  { name: "", value: "Web design and website development" },
  { name: "", value: "Administration" },
  { name: "", value: "Internet connection" },
  { name: "", value: "Domain sale" },
  { name: "", value: "Domain registration" },
  { name: "", value: "Hosting" },
  { name: "", value: "Miscellaneous" },
];

export const miscellaneous = [{ name: "", value: "Others" }];
